/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DaoConnection;
import db.GenerateOtp;
import db.SmsZone;
import java.awt.Dimension;
import java.awt.Frame;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JPanel {

    DaoConnection dc = new DaoConnection();
    Connection con;
//    public static Stri MainFrame mainFrame;
    static String otp = "";
    Frame frm;
    public static String isStatus = "";

    public Login(Frame frm) {
        this.frm = frm;
        initComponents();

        con = dc.getConnection();
//        mainFrame.setSize(350, 350);
//        mainFrame.setLocationRelativeTo(null);
//        jrUserCheck.setSelected(true);
//        loginUser="user";
        frm.setExtendedState(MAXIMIZED_BOTH);
        if (MainPln.status.equalsIgnoreCase("Teacher")) {
//            frm.setSize(350, 600);
            frm.setLocationRelativeTo(null);
            pnlChange.removeAll();
            pnlChange.add(pnlTeach);
            pnlChange.updateUI();
        } else {
//            frm.setSize(350, 650);
            frm.setLocationRelativeTo(null);
        }
//        student.setVisible(false);
//        teacher.setVisible(false);
        txtOtp.setEnabled(false);
        btnLogin.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTeach = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtUserNameT = new javax.swing.JTextField();
        txtPasswordT = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JcType = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        BtnLoginTeacher = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlChange = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jc_choice = new javax.swing.JComboBox();
        student = new javax.swing.JRadioButton();
        teacher = new javax.swing.JRadioButton();
        btnOtp = new javax.swing.JButton();
        txtOtp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        pnlTeach.setBackground(new java.awt.Color(26, 42, 57));
        pnlTeach.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(26, 42, 57));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Vivaldi", 3, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Welcome");
        jLabel5.setMinimumSize(new java.awt.Dimension(170, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 103;
        gridBagConstraints.ipady = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(96, 63, 0, 64);
        jPanel4.add(jLabel5, gridBagConstraints);

        txtUserNameT.setMaximumSize(new java.awt.Dimension(100, 30));
        txtUserNameT.setMinimumSize(new java.awt.Dimension(100, 30));
        txtUserNameT.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 140;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 63, 0, 0);
        jPanel4.add(txtUserNameT, gridBagConstraints);

        txtPasswordT.setMaximumSize(new java.awt.Dimension(100, 30));
        txtPasswordT.setMinimumSize(new java.awt.Dimension(100, 30));
        txtPasswordT.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 140;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 63, 0, 0);
        jPanel4.add(txtPasswordT, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 63, 0, 0);
        jPanel4.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 63, 0, 0);
        jPanel4.add(jLabel7, gridBagConstraints);

        JcType.setForeground(new java.awt.Color(26, 42, 57));
        JcType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Subject Teacher", "Class Teacher", "H.O.D" }));
        JcType.setMaximumSize(new java.awt.Dimension(230, 27));
        JcType.setMinimumSize(new java.awt.Dimension(230, 27));
        JcType.setPreferredSize(new java.awt.Dimension(230, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 63, 0, 0);
        jPanel4.add(JcType, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Select Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 63, 0, 0);
        jPanel4.add(jLabel8, gridBagConstraints);

        BtnLoginTeacher.setBackground(new java.awt.Color(255, 255, 255));
        BtnLoginTeacher.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnLoginTeacher.setForeground(new java.awt.Color(26, 42, 57));
        BtnLoginTeacher.setText("Login");
        BtnLoginTeacher.setMaximumSize(new java.awt.Dimension(127, 30));
        BtnLoginTeacher.setMinimumSize(new java.awt.Dimension(127, 30));
        BtnLoginTeacher.setPreferredSize(new java.awt.Dimension(127, 30));
        BtnLoginTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginTeacherActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 63, 0, 0);
        jPanel4.add(BtnLoginTeacher, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("MS PMincho", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Don't have a Teacher's account?");
        jLabel9.setMinimumSize(new java.awt.Dimension(34, 14));
        jLabel9.setPreferredSize(new java.awt.Dimension(34, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 63, 0, 0);
        jPanel4.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" Click here");
        jLabel10.setMinimumSize(new java.awt.Dimension(50, 16));
        jLabel10.setPreferredSize(new java.awt.Dimension(50, 16));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 2, 0, 0);
        jPanel4.add(jLabel10, gridBagConstraints);

        btnBack1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 63, 42, 0);
        jPanel4.add(btnBack1, gridBagConstraints);

        pnlTeach.add(jPanel4, java.awt.BorderLayout.CENTER);

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(26, 42, 57));
        jPanel2.setLayout(new java.awt.BorderLayout());

        pnlChange.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(26, 42, 57));
        jPanel1.setMinimumSize(new java.awt.Dimension(335, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(335, 400));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtEmail.setBackground(new java.awt.Color(253, 253, 253));
        txtEmail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtEmail.setMinimumSize(new java.awt.Dimension(15, 20));
        txtEmail.setPreferredSize(new java.awt.Dimension(15, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 83, 0, 0);
        jPanel1.add(txtEmail, gridBagConstraints);

        txtPassword.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtPassword.setMinimumSize(new java.awt.Dimension(15, 20));
        txtPassword.setPreferredSize(new java.awt.Dimension(15, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 83, 0, 0);
        jPanel1.add(txtPassword, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 83, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 43;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 83, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Vivaldi", 3, 50)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Welcome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(102, 110, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jc_choice.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jc_choice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "----- Select -----", "Registration", "Print ID Card", "Edit Records" }));
        jc_choice.setMinimumSize(new java.awt.Dimension(150, 27));
        jc_choice.setPreferredSize(new java.awt.Dimension(150, 27));
        jc_choice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_choiceActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 83, 0, 0);
        jPanel1.add(jc_choice, gridBagConstraints);

        student.setBackground(new java.awt.Color(26, 42, 57));
        student.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        student.setForeground(new java.awt.Color(255, 255, 255));
        student.setText("Student");
        student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        jPanel1.add(student, gridBagConstraints);

        teacher.setBackground(new java.awt.Color(26, 42, 57));
        teacher.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        teacher.setForeground(new java.awt.Color(255, 255, 255));
        teacher.setText("Teacher");
        teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 83, 0, 0);
        jPanel1.add(teacher, gridBagConstraints);

        btnOtp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnOtp.setText("Generate OTP");
        btnOtp.setMaximumSize(new java.awt.Dimension(120, 30));
        btnOtp.setMinimumSize(new java.awt.Dimension(115, 30));
        btnOtp.setPreferredSize(new java.awt.Dimension(120, 30));
        btnOtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 123;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 83, 0, 79);
        jPanel1.add(btnOtp, gridBagConstraints);

        txtOtp.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtOtp.setMaximumSize(new java.awt.Dimension(18, 30));
        txtOtp.setMinimumSize(new java.awt.Dimension(18, 30));
        txtOtp.setPreferredSize(new java.awt.Dimension(18, 30));
        txtOtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 215;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 83, 0, 0);
        jPanel1.add(txtOtp, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter OTP :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 83, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        btnLogin.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setMaximumSize(new java.awt.Dimension(100, 30));
        btnLogin.setMinimumSize(new java.awt.Dimension(75, 30));
        btnLogin.setPreferredSize(new java.awt.Dimension(75, 30));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 83, 0, 0);
        jPanel1.add(btnLogin, gridBagConstraints);

        btnBack.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 174;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 83, 32, 0);
        jPanel1.add(btnBack, gridBagConstraints);

        pnlChange.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.add(pnlChange, java.awt.BorderLayout.CENTER);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void jc_choiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_choiceActionPerformed
        String stutus = (String) jc_choice.getSelectedItem();
//        if (stutus.equalsIgnoreCase("Registration")) {
//            student.setVisible(true);
//            teacher.setVisible(true);
//
//        } else {
//            student.setVisible(false);
//            teacher.setVisible(false);
//        }
    }//GEN-LAST:event_jc_choiceActionPerformed

    private void studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentActionPerformed

        if (student.isSelected()) {
            teacher.setSelected(false);
        }
    }//GEN-LAST:event_studentActionPerformed

    private void teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherActionPerformed
        if (teacher.isSelected()) {
            student.setSelected(false);
        }
    }//GEN-LAST:event_teacherActionPerformed

    private void btnOtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtpActionPerformed
        // TODO add your handling code here:
        //        GUI_MAIN.MainPanel.setSize(850, 730);
        //                                gui.setSize(screenSize);

        //        gui.setVisible(true);
        //        this.dispose();
        try {
//            String contact = "";
            String user = txtEmail.getText();
            String pass = new String(txtPassword.getPassword());
            PreparedStatement ps;
            if ((!user.equals("")) && (!pass.equals(""))) {
                if ((!user.equals("")) || (!pass.equals(""))) {
                    if (jc_choice.getSelectedItem().equals("Attendance")) {
                        ps = con.prepareStatement("select * from tbtecher where username='" + user + "'&&password='" + pass + "'");
                    } else {
                        ps = con.prepareStatement("select * from logintbl where username='" + user + "'&&password='" + pass + "'");
                    }
                    ResultSet set = ps.executeQuery();
                    while (set.next()) {
                        String contact = set.getString("contact");
                        txtOtp.setEnabled(true);
                        btnLogin.setEnabled(true);
                        otp = new GenerateOtp().generateKey();
                        //            PreparedStatement ps1 = conn.prepareStatement("insert into otpstore values (?)");
                        //            ps1.setString(1, otp);
                        //            ps.execute();
                        new SmsZone().SendToSms(otp.trim(), contact);
                        JOptionPane.showMessageDialog(null, "OTP Send to Register Mobile Number !!!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please Enter Username or Password !!!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please Enter Username and Password !!!");
            }
//            con.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnOtpActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (("".equals(txtEmail.getText())) || ("".equals(txtPassword.getText()))) {
            JOptionPane.showMessageDialog(null, "Please Enter all the Fields !!!");
        } else {
            jc_choice.getSelectedItem();
            System.out.println("" + otp);
            if (otp.equals(txtOtp.getText().trim())) {
                if (jc_choice.getSelectedItem().equals("Registration")) {

                    String stuts = "";
                    if (student.isSelected()) {
                        stuts = "student";
                    } else if (teacher.isSelected()) {
                        stuts = "teacher";
                    }
                    if (stuts.equalsIgnoreCase("student")) {
                        try {
                            String username = txtEmail.getText();
                            String password = txtPassword.getText();
//                            Connection conn = null;
//                            DaoConnection dao = new DaoConnection();
//                            conn = dao.getConnection();
                            PreparedStatement ps;
                            ps = con.prepareStatement("select * from logintbl where username=? and password=? ");
                            ps.setString(1, username);
                            ps.setString(2, password);
                            ResultSet rs = ps.executeQuery();
                            if (rs.next()) {
//                                JOptionPane.showMessageDialog(null, "Login Successful !!!");
                                MainPln.PnelMn.setSize(850, 730);
                                //                                gui.setSize(screenSize);
                                MainPln.PnelMn.removeAll();
                                MainPln.PnelMn.add(new Student_Registration(frm));
                                //                        gui.MainPanel.add(new Teacher_Registration(gui));
                                MainPln.PnelMn.updateUI();
//                                GUI_MAIN.setVisible(true);
//                                this.dispose();
                            } else {
                                JOptionPane.showMessageDialog(null, "Incorrect Username or Password... Try Again !!!");
                            }
                        } catch (SQLException ex) {
                            System.out.println("Exceptionm : " + ex);
                        }
                    } else if (stuts.equalsIgnoreCase("teacher")) {
                        try {
                            String username = txtEmail.getText();
                            String password = txtPassword.getText();
//                            Connection conn = null;
//                            DaoConnection dao = new DaoConnection();
//                            conn = dao.getConnection();
                            PreparedStatement ps;
                            ps = con.prepareStatement("select * from logintbl where username=? and password=? ");
                            ps.setString(1, username);
                            ps.setString(2, password);
                            ResultSet rs = ps.executeQuery();
                            if (rs.next()) {
//                                JOptionPane.showMessageDialog(null, "Login Successful !!!");
//                                MainPln.PnelMn.setSize(850, 730);
                                MainPln.PnelMn.removeAll();
                                //                            gui.MainPanel.add(new Student_Registration(gui));
                                MainPln.PnelMn.add(new TeacherReg1(frm));
                                MainPln.PnelMn.updateUI();
//                                GUI_MAIN.setVisible(true);
//                                this.dispose();
                            } else {
                                JOptionPane.showMessageDialog(null, "Incorrect Username or Password... Try Again !!!");
                            }
                        } catch (SQLException ex) {
                            System.out.println("Exceptionm : " + ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Something Is Missing... ");
                    }
                } else if (jc_choice.getSelectedItem().equals("Print ID Card")) {
                    try {
                        String username = txtEmail.getText();
                        String password = txtPassword.getText();
//                        Connection conn = null;
//                        DaoConnection dao = new DaoConnection();
//
//                        conn = dao.getConnection();
                        PreparedStatement ps;

                        ps = con.prepareStatement("select * from logintbl where username=? and password=? ");
                        ps.setString(1, username);
                        ps.setString(2, password);
                        ResultSet rs = ps.executeQuery();
                        if (rs.next()) {
//                            JOptionPane.showMessageDialog(null, "Login Successful !!!");

                            //                        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                            //                                gui.setExtendedState(MAXIMIZED_BOTH);
                            //                        gui.setLocation(screenSize.width / 2 - gui.getSize().width / 2, screenSize.height / 2 - gui.getSize().height / 2);
                            String stuts = "";
                            if (student.isSelected()) {
                                stuts = "student";
                                MainPln.PnelMn.setSize(850, 730);
                                MainPln.PnelMn.removeAll();
                                MainPln.PnelMn.add(new GenerateID(frm));
                                MainPln.PnelMn.updateUI();

                            } else if (teacher.isSelected()) {
                                stuts = "teacher";
                                MainPln.PnelMn.setSize(850, 730);
                                MainPln.PnelMn.removeAll();
                                MainPln.PnelMn.add(new GenerateIDTech(frm));
                                MainPln.PnelMn.updateUI();
//                                con.close();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Incorrect Username or Password... Try Again !!!");
                        }
                    } catch (SQLException ex) {
                        System.out.println("Exceptionm : " + ex);
                    }
                } else if (jc_choice.getSelectedItem().equals("Edit Records")) {
                    try {
                        String email = txtEmail.getText();
                        String pass = new String(txtPassword.getPassword());
                        PreparedStatement ps = con.prepareStatement("select * from logintbl where username='" + email + "'&&password='" + pass + "'");
                        ResultSet set = ps.executeQuery();

                        while (set.next()) {
                            if (student.isSelected()) {
                                isStatus = "Student Edit";
                                MainPln.PnelMn.removeAll();
                                MainPln.PnelMn.add(new Student_Registration(frm));
                                MainPln.PnelMn.updateUI();
                            } else if (teacher.isSelected()) {
                                isStatus = "Teacher Edit";
                                MainPln.PnelMn.removeAll();
                                MainPln.PnelMn.add(new TeacherReg1(frm));
                                MainPln.PnelMn.updateUI();
                            }

//                            con.close();
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }

//                else {
//                    try {
//                        String user = txtEmail.getText();
//                        String pass = new String(txtPassword.getPassword());
//                        PreparedStatement ps = con.prepareStatement("select * from tbtecher where first='" + user + "'&&pass='" + pass + "'");
//                        ResultSet executeQuery = ps.executeQuery();
//                        System.out.println("yess");
//                        if (executeQuery.next()) {
//                            System.out.println("true");
//                            MainPln.PnelMn.removeAll();
//                            MainPln.PnelMn.add(new pnlAttendance1());
//                            MainPln.PnelMn.updateUI();
//                        } else {
//                            JOptionPane.showMessageDialog(null, "Invalid User Name or Password and Teacher Login Only");
//                        }
//
//                    } catch (Exception e) {
//                        e.printStackTrace();
//                    }
//                }
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect OTP...");
            }
        }

    }//GEN-LAST:event_btnLoginActionPerformed
    public static String userName;
    public static String typeTeacher;
    private void BtnLoginTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginTeacherActionPerformed
        // TODO add your handling code here:
        try {
            int index = JcType.getSelectedIndex();
            PreparedStatement ps;
            userName = txtUserNameT.getText();
            String pass = new String(txtPasswordT.getPassword());
            if (userName.equals("") || pass.equals("")) {
                JOptionPane.showMessageDialog(null, "Enter Username or Password !!!");
            } else {
                if (index == 0) {
                    JOptionPane.showMessageDialog(null, "Please Select Teacher Type");
                } else if (index == 1) {
                    ps = con.prepareStatement("select * from subject_teacher where username='" + userName + "'&&password='" + pass + "'");
                    ResultSet set = ps.executeQuery();
                    if (set.next()) {
                        typeTeacher = (String) JcType.getSelectedItem();
                        System.out.println("typeTeacher : " + typeTeacher);
                        System.out.println("yess");
                        MainPln.PnelMn.removeAll();
                        MainPln.PnelMn.add(new pnlAttendance1(frm));
                        MainPln.PnelMn.updateUI();
                    } else {
                        JOptionPane.showMessageDialog(null, "Incorrect Username or Password... Try Again !!!");
                    }
                } else if (index == 2) {
                    ps = con.prepareStatement("select * from class_teacher where username='" + userName + "'&&password='" + pass + "'");
                    ResultSet set = ps.executeQuery();
                    if (set.next()) {
                        System.out.println("yesssss");
                        typeTeacher = (String) JcType.getSelectedItem();
                        MainPln.PnelMn.removeAll();
                        MainPln.PnelMn.add(new pnlAttendance1(frm));
                        MainPln.PnelMn.updateUI();
                    } else {
                        JOptionPane.showMessageDialog(null, "Incorrect Username or Password... Try Again !!!");
                    }
                } else if (index == 3) {
                    ps = con.prepareStatement("select * from hod where username='" + userName + "'&&password='" + pass + "'");
                    ResultSet set = ps.executeQuery();
                    if (set.next()) {
                        typeTeacher = (String) JcType.getSelectedItem();
                        MainPln.PnelMn.removeAll();
                        MainPln.PnelMn.add(new pnlAttendance1(frm));
                        MainPln.PnelMn.updateUI();
                        System.out.println("yessssssssss");
                    } else {
                        JOptionPane.showMessageDialog(null, "Incorrect Username or Password... Try Again !!!");
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnLoginTeacherActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:

        MainPln.PnelMn.removeAll();
        MainPln.PnelMn.add(new Reg_Pnl(frm));
        MainPln.PnelMn.updateUI();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txtOtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtpActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainPln.PnelMn.removeAll();
        MainPln.PnelMn.add(new MainPln((JFrame) frm));
        MainPln.PnelMn.updateUI();

//        frame.add(new MainPln(frame));
////        frame.setLocationRelativeTo(null);
////        frame.setExtendedState(BaseRootPaneUI.MAXIMIZED_BOTH);
//        frame.setVisible(true);
//        frame.setSize(600, 300);
//        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
//        frame.setLocation(dim.width / 2 - frame.getSize().width / 2, dim.height / 2 - frame.getSize().height / 2);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        MainPln.PnelMn.removeAll();
        MainPln.PnelMn.add(new MainPln((JFrame) frm));
        MainPln.PnelMn.updateUI();
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLoginTeacher;
    private javax.swing.JComboBox JcType;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnOtp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox jc_choice;
    private javax.swing.JPanel pnlChange;
    private javax.swing.JPanel pnlTeach;
    private javax.swing.JRadioButton student;
    private javax.swing.JRadioButton teacher;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOtp;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordT;
    private javax.swing.JTextField txtUserNameT;
    // End of variables declaration//GEN-END:variables
}
