/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

public class MainPln extends javax.swing.JPanel {

    JFrame frm;

    public MainPln(JFrame frm) {
        this.frm = frm;
        initComponents();
        rbGenerate.setSelected(true);
        frm.setVisible(true);
        frm.setSize(600, 300);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        frm.setLocation(dim.width / 2 - frm.getSize().width / 2, dim.height / 2 - frm.getSize().height / 2);

//        PnelMn.removeAll();
//        PnelMn.add(new Reg_Pnl());
//        PnelMn.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnelMn = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rbTeacher = new javax.swing.JRadioButton();
        rbGenerate = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        PnelMn.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(26, 42, 57));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        rbTeacher.setBackground(new java.awt.Color(26, 42, 57));
        rbTeacher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbTeacher.setForeground(new java.awt.Color(255, 255, 255));
        rbTeacher.setText("Attendance");
        rbTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTeacherActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 52, 0, 139);
        jPanel5.add(rbTeacher, gridBagConstraints);

        rbGenerate.setBackground(new java.awt.Color(26, 42, 57));
        rbGenerate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbGenerate.setForeground(new java.awt.Color(255, 255, 255));
        rbGenerate.setText("ID Card");
        rbGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGenerateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 139, 0, 0);
        jPanel5.add(rbGenerate, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(26, 42, 57));
        jButton1.setText("Proceed >>>");
        jButton1.setMaximumSize(new java.awt.Dimension(80, 35));
        jButton1.setMinimumSize(new java.awt.Dimension(80, 35));
        jButton1.setPreferredSize(new java.awt.Dimension(80, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 175;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 139, 50, 139);
        jPanel5.add(jButton1, gridBagConstraints);

        PnelMn.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(PnelMn, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void rbGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGenerateActionPerformed
        // TODO add your handling code here:
        if (rbGenerate.isSelected()) {
//            rbRegTeach.setSelected(false);
            rbTeacher.setSelected(false);
        }
    }//GEN-LAST:event_rbGenerateActionPerformed

    private void rbTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTeacherActionPerformed
        // TODO add your handling code here:
        if (rbTeacher.isSelected()) {
//            rbRegTeach.setSelected(false);
            rbGenerate.setSelected(false);
        }
    }//GEN-LAST:event_rbTeacherActionPerformed
    public static String status = "";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//       System.out.println(""+rbRegTeach.getText());
//        System.out.println(""+rbTeacher.getText());
//        System.out.println(""+rbGenerate.getText());

        if (rbTeacher.isSelected()) {
            status = "Teacher";
        } else if (rbGenerate.isSelected()) {
            status = "Generate ID";
        }
        if (status.equalsIgnoreCase("Teacher Register")) {
//            System.out.println("" + rbRegTeach.getText());
            PnelMn.removeAll();
            PnelMn.add(new Reg_Pnl(frm));
            PnelMn.updateUI();
            PnelMn.setSize(300, 600);
        } else if (status.equalsIgnoreCase("Teacher")) {
//            System.out.println("" + rbTeacher.getText());
            PnelMn.removeAll();
            PnelMn.add(new Login(frm));
            PnelMn.updateUI();
            PnelMn.setSize(300, 600);
        } else if (status.equalsIgnoreCase("Generate ID")) {
//            System.out.println("" + rbGenerate.getText());
            MainPln.PnelMn.setSize(850, 730);
            //                                gui.setSize(screenSize);
//        MainPln.PnelMn.removeAll();
//        MainPln.PnelMn.add(new GenerateID());
//        MainPln.PnelMn.updateUI();

            PnelMn.removeAll();
            PnelMn.add(new Login(frm));
            PnelMn.updateUI();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel PnelMn;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton rbGenerate;
    private javax.swing.JRadioButton rbTeacher;
    // End of variables declaration//GEN-END:variables
}
