/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DaoConnection;
import dao.DaoConnection1;
import java.awt.Frame;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tulajaram
 */
public class Reg_Pnl extends javax.swing.JPanel {

    /**
     * Creates new form Reg_Pnl
     */
    DaoConnection dc = new DaoConnection();
    Connection con;
    DefaultListModel listModel = new DefaultListModel();
    DaoConnection1 dc1 = new DaoConnection1();
    Connection con11;
    Frame frm;
    ArrayList<String> allSubject = new ArrayList<>();
    int val = 0;
    

    public Reg_Pnl(Frame frm) {
        this.frm = frm;
//        jcSubjectTypeS.setVisible(false);
        initComponents();
        con = dc.getConnection();
        con11 = dc.getConnection();
        frm.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PnlSubject = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsernameS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPasswordS = new javax.swing.JPasswordField();
        txtRePasswordS = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jcDepartmentS = new javax.swing.JComboBox();
        jcSem = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jcYearS = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        JcShiftS = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcSubjectTypeS = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSubject = new javax.swing.JList();
        PnlClass = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtUsernameC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcDepartmentC = new javax.swing.JComboBox();
        txtPasswordC = new javax.swing.JPasswordField();
        txtRePasswordC = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jcYearC = new javax.swing.JComboBox();
        jcShiftC = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        HODpnl = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtUserNameH = new javax.swing.JTextField();
        txtRePasswordH = new javax.swing.JPasswordField();
        txtPasswordH = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jcDepartmentH = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        pnlHomePnl = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jcType = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        BtnRegister = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();

        PnlSubject.setLayout(new javax.swing.BoxLayout(PnlSubject, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(26, 42, 57));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 100, 0, 0);
        jPanel4.add(jLabel1, gridBagConstraints);

        txtUsernameS.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtUsernameS.setForeground(new java.awt.Color(26, 42, 57));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 314;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 0, 0);
        jPanel4.add(txtUsernameS, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 0, 0);
        jPanel4.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Re-Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 0, 0);
        jPanel4.add(jLabel3, gridBagConstraints);

        txtPasswordS.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtPasswordS.setForeground(new java.awt.Color(26, 42, 57));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 314;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 0, 0);
        jPanel4.add(txtPasswordS, gridBagConstraints);

        txtRePasswordS.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtRePasswordS.setForeground(new java.awt.Color(26, 42, 57));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 314;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 0, 0);
        jPanel4.add(txtRePasswordS, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 0, 0);
        jPanel4.add(jLabel4, gridBagConstraints);

        jcDepartmentS.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jcDepartmentS.setForeground(new java.awt.Color(26, 42, 57));
        jcDepartmentS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Department", "CO", "ME", "Civil", "EJ", "IF" }));
        jcDepartmentS.setMaximumSize(new java.awt.Dimension(200, 30));
        jcDepartmentS.setMinimumSize(new java.awt.Dimension(200, 30));
        jcDepartmentS.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 121;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 0, 0);
        jPanel4.add(jcDepartmentS, gridBagConstraints);

        jcSem.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jcSem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Semister", "1", "2", "3", "4", "5", "6" }));
        jcSem.setMinimumSize(new java.awt.Dimension(70, 30));
        jcSem.setPreferredSize(new java.awt.Dimension(70, 30));
        jcSem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcSemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 253;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 30, 0);
        jPanel4.add(jcSem, gridBagConstraints);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Semister");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 0, 0);
        jPanel4.add(jLabel21, gridBagConstraints);

        PnlSubject.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(26, 42, 57));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 162, 0, 0);
        jPanel5.add(jLabel5, gridBagConstraints);

        jcYearS.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jcYearS.setForeground(new java.awt.Color(26, 42, 57));
        jcYearS.setToolTipText("");
        jcYearS.setMaximumSize(new java.awt.Dimension(200, 30));
        jcYearS.setMinimumSize(new java.awt.Dimension(20, 30));
        jcYearS.setPreferredSize(new java.awt.Dimension(20, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 326;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 162, 0, 54);
        jPanel5.add(jcYearS, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Shift");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 162, 0, 0);
        jPanel5.add(jLabel6, gridBagConstraints);

        JcShiftS.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        JcShiftS.setForeground(new java.awt.Color(26, 42, 57));
        JcShiftS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II" }));
        JcShiftS.setMaximumSize(new java.awt.Dimension(200, 30));
        JcShiftS.setMinimumSize(new java.awt.Dimension(20, 30));
        JcShiftS.setPreferredSize(new java.awt.Dimension(20, 30));
        JcShiftS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcShiftSActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 326;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 162, 0, 54);
        jPanel5.add(JcShiftS, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Subject");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 162, 0, 0);
        jPanel5.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Subject Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 162, 0, 0);
        jPanel5.add(jLabel8, gridBagConstraints);

        jcSubjectTypeS.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jcSubjectTypeS.setForeground(new java.awt.Color(26, 42, 57));
        jcSubjectTypeS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TH", "PR" }));
        jcSubjectTypeS.setMaximumSize(new java.awt.Dimension(200, 30));
        jcSubjectTypeS.setMinimumSize(new java.awt.Dimension(20, 30));
        jcSubjectTypeS.setPreferredSize(new java.awt.Dimension(20, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 326;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 162, 30, 54);
        jPanel5.add(jcSubjectTypeS, gridBagConstraints);

        jPanel8.setMaximumSize(new java.awt.Dimension(10, 23));
        jPanel8.setMinimumSize(new java.awt.Dimension(10, 23));
        jPanel8.setPreferredSize(new java.awt.Dimension(0, 23));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(20, 30));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(20, 30));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(20, 30));

        lstSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstSubjectMouseClicked(evt);
            }
        });
        lstSubject.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstSubjectKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstSubject);

        jPanel8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 336;
        gridBagConstraints.ipady = 107;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 162, 0, 54);
        jPanel5.add(jPanel8, gridBagConstraints);

        PnlSubject.add(jPanel5);

        PnlClass.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(26, 42, 57));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 409, 0, 0);
        jPanel3.add(jLabel9, gridBagConstraints);

        txtUsernameC.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtUsernameC.setForeground(new java.awt.Color(26, 42, 57));
        txtUsernameC.setMaximumSize(new java.awt.Dimension(135, 30));
        txtUsernameC.setMinimumSize(new java.awt.Dimension(135, 30));
        txtUsernameC.setPreferredSize(new java.awt.Dimension(135, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 409, 0, 409);
        jPanel3.add(txtUsernameC, gridBagConstraints);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 409, 0, 0);
        jPanel3.add(jLabel10, gridBagConstraints);

        jcDepartmentC.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jcDepartmentC.setForeground(new java.awt.Color(26, 42, 57));
        jcDepartmentC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Department", "ME", "Civil", "EJ", "CO", "IF" }));
        jcDepartmentC.setMaximumSize(new java.awt.Dimension(250, 30));
        jcDepartmentC.setMinimumSize(new java.awt.Dimension(250, 30));
        jcDepartmentC.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 409, 0, 0);
        jPanel3.add(jcDepartmentC, gridBagConstraints);

        txtPasswordC.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtPasswordC.setForeground(new java.awt.Color(26, 42, 57));
        txtPasswordC.setMaximumSize(new java.awt.Dimension(150, 30));
        txtPasswordC.setMinimumSize(new java.awt.Dimension(150, 30));
        txtPasswordC.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 409, 0, 409);
        jPanel3.add(txtPasswordC, gridBagConstraints);

        txtRePasswordC.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtRePasswordC.setForeground(new java.awt.Color(26, 42, 57));
        txtRePasswordC.setMaximumSize(new java.awt.Dimension(150, 30));
        txtRePasswordC.setMinimumSize(new java.awt.Dimension(150, 30));
        txtRePasswordC.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 409, 0, 409);
        jPanel3.add(txtRePasswordC, gridBagConstraints);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Re-Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 409, 0, 0);
        jPanel3.add(jLabel11, gridBagConstraints);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DepartMent");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 409, 0, 0);
        jPanel3.add(jLabel12, gridBagConstraints);

        jcYearC.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jcYearC.setForeground(new java.awt.Color(26, 42, 57));
        jcYearC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FY", "SY", "TY" }));
        jcYearC.setMaximumSize(new java.awt.Dimension(250, 30));
        jcYearC.setMinimumSize(new java.awt.Dimension(250, 30));
        jcYearC.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 409, 0, 0);
        jPanel3.add(jcYearC, gridBagConstraints);

        jcShiftC.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jcShiftC.setForeground(new java.awt.Color(26, 42, 57));
        jcShiftC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II" }));
        jcShiftC.setMaximumSize(new java.awt.Dimension(250, 30));
        jcShiftC.setMinimumSize(new java.awt.Dimension(250, 30));
        jcShiftC.setPreferredSize(new java.awt.Dimension(250, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 409, 20, 0);
        jPanel3.add(jcShiftC, gridBagConstraints);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 409, 0, 0);
        jPanel3.add(jLabel13, gridBagConstraints);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Shift");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 409, 0, 0);
        jPanel3.add(jLabel14, gridBagConstraints);

        PnlClass.add(jPanel3, java.awt.BorderLayout.CENTER);

        HODpnl.setLayout(new javax.swing.BoxLayout(HODpnl, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setBackground(new java.awt.Color(26, 42, 57));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 407, 0, 0);
        jPanel7.add(jLabel15, gridBagConstraints);

        txtUserNameH.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtUserNameH.setForeground(new java.awt.Color(26, 42, 57));
        txtUserNameH.setMaximumSize(new java.awt.Dimension(125, 30));
        txtUserNameH.setMinimumSize(new java.awt.Dimension(125, 30));
        txtUserNameH.setPreferredSize(new java.awt.Dimension(125, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 76;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 407, 0, 0);
        jPanel7.add(txtUserNameH, gridBagConstraints);

        txtRePasswordH.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtRePasswordH.setForeground(new java.awt.Color(26, 42, 57));
        txtRePasswordH.setMaximumSize(new java.awt.Dimension(100, 30));
        txtRePasswordH.setMinimumSize(new java.awt.Dimension(100, 30));
        txtRePasswordH.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 407, 0, 407);
        jPanel7.add(txtRePasswordH, gridBagConstraints);

        txtPasswordH.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtPasswordH.setForeground(new java.awt.Color(26, 42, 57));
        txtPasswordH.setMaximumSize(new java.awt.Dimension(100, 30));
        txtPasswordH.setMinimumSize(new java.awt.Dimension(100, 30));
        txtPasswordH.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 105;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 407, 0, 407);
        jPanel7.add(txtPasswordH, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 407, 0, 0);
        jPanel7.add(jLabel16, gridBagConstraints);

        jcDepartmentH.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jcDepartmentH.setForeground(new java.awt.Color(26, 42, 57));
        jcDepartmentH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Department", "ME", "Civil", "EJ", "CO", "IF" }));
        jcDepartmentH.setMaximumSize(new java.awt.Dimension(200, 30));
        jcDepartmentH.setMinimumSize(new java.awt.Dimension(200, 30));
        jcDepartmentH.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 407, 50, 0);
        jPanel7.add(jcDepartmentH, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Re-Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 407, 0, 0);
        jPanel7.add(jLabel17, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 407, 0, 0);
        jPanel7.add(jLabel18, gridBagConstraints);

        HODpnl.add(jPanel7);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlMain.setLayout(new java.awt.BorderLayout());

        pnlHomePnl.setBackground(new java.awt.Color(26, 42, 57));
        pnlHomePnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlHomePnl.setLayout(new java.awt.BorderLayout());
        pnlMain.add(pnlHomePnl, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnlMain, java.awt.BorderLayout.CENTER);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(26, 42, 57));
        jLabel19.setText("Select Type");
        jLabel19.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel9.add(jLabel19);

        jcType.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jcType.setForeground(new java.awt.Color(26, 42, 57));
        jcType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Subject Teacher", "Class Teacher", "H.O.D." }));
        jcType.setPreferredSize(new java.awt.Dimension(200, 30));
        jcType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTypeActionPerformed(evt);
            }
        });
        jPanel9.add(jcType);

        jPanel1.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(26, 42, 57));

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Teacher's Registration");
        jLabel20.setPreferredSize(new java.awt.Dimension(228, 30));
        jPanel2.add(jLabel20);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        BtnRegister.setBackground(new java.awt.Color(26, 42, 57));
        BtnRegister.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegister.setText("Register");
        BtnRegister.setPreferredSize(new java.awt.Dimension(120, 30));
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });
        jPanel6.add(BtnRegister);

        btnReset.setBackground(new java.awt.Color(26, 42, 57));
        btnReset.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.setPreferredSize(new java.awt.Dimension(120, 30));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel6.add(btnReset);

        BtnBack.setBackground(new java.awt.Color(26, 42, 57));
        BtnBack.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnBack.setForeground(new java.awt.Color(255, 255, 255));
        BtnBack.setText("Back");
        BtnBack.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        jPanel6.add(BtnBack);

        add(jPanel6, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jcTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTypeActionPerformed
        // TODO add your handling code here:
        if (jcType.getSelectedIndex() == 0) {
            pnlMain.removeAll();
            pnlMain.add(pnlHomePnl);
            pnlMain.updateUI();
        } else if (jcType.getSelectedIndex() == 1) {
            createTable("subject_teacher");
            createTable5("subject_list");
            pnlMain.removeAll();
            pnlMain.add(PnlSubject);
            pnlMain.updateUI();
        } else if (jcType.getSelectedIndex() == 2) {
            createTable1("class_teacher");
            pnlMain.removeAll();
            pnlMain.add(PnlClass);
            pnlMain.updateUI();

        } else if (jcType.getSelectedIndex() == 3) {
            createTable2("hod");
            pnlMain.removeAll();
            pnlMain.add(HODpnl);
            pnlMain.updateUI();
        }
    }//GEN-LAST:event_jcTypeActionPerformed
    List selectSubjectList;
    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        int index = jcType.getSelectedIndex();
        if (index == 0) {
            JOptionPane.showMessageDialog(null, "Please Select Type !!!");
        } else if (index == 1) {
            try {
                String subject = "";
                String pass = new String(txtPasswordS.getPassword());
                String rePass = new String(txtRePasswordS.getPassword());
                String userName = txtUsernameS.getText();
                int semIndex = jcSem.getSelectedIndex();
                //                String subject = txtSubjectS.getText();
                selectSubjectList = lstSubject.getSelectedValuesList();
//                System.out.println(">>><<<<" + selectSubjectList);
                for (int i = 0; i < selectSubjectList.size(); i++) {
                    String get = selectSubjectList.get(i).toString();
                    if (!v.contains(get)) {
                        v.add(get);
                    }
                }

                if (v.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please Select Subject First !!!");
                } else {
                    for (int i = 0; i < v.size(); i++) {
                        String get = (String) v.get(i);
                        subject = get + "," + subject;
                    }
                    System.out.println(">>><<<<" + subject);
                }
//                String replaceAll = subject.replaceAll(" ,", "  ");
//                String reString=replaceAll.trim().replaceAll("  ", ",");
                StringBuilder b = new StringBuilder(subject);
                b.replace(subject.lastIndexOf(","), subject.lastIndexOf(",") + 1, "");
                subject = b.toString();
                String restring = subject.replaceAll(" ,", ",");
                String Dept = (String) jcDepartmentS.getSelectedItem();
                String shift = (String) JcShiftS.getSelectedItem();
                String year = (String) jcYearS.getSelectedItem();
                String subType = (String) jcSubjectTypeS.getSelectedItem();
                if (pass.equals("") || rePass.equals("") || userName.equals("") || jcDepartmentS.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Please Enter All the Fields !!!");
                } else {
                    con = dc.getConnection();
                    ps = con.prepareStatement("insert into subject_teacher values(?,?,?,?,?,?,?)");

                    if (pass.equals(rePass)) {
                        ps.setString(1, userName);
                        ps.setString(2, pass);
                        ps.setString(3, Dept);
                        ps.setString(4, year);
                        ps.setString(5, shift);
                        ps.setString(6, restring);
                        ps.setString(7, subType);
                        ps.execute();

                        JOptionPane.showMessageDialog(null, "Account Created Successfully !!!");
                        txtPasswordC.setText("");
                        txtPasswordH.setText("");
                        txtPasswordS.setText("");
                        txtRePasswordC.setText("");
                        txtRePasswordH.setText("");
                        txtRePasswordS.setText("");
                        txtUserNameH.setText("");
                        txtUsernameC.setText("");
                        txtUsernameS.setText("");

                        jcDepartmentC.setSelectedIndex(0);
                        jcDepartmentH.setSelectedIndex(0);
                        jcDepartmentS.setSelectedIndex(0);
                        jcShiftC.setSelectedIndex(0);
                        jcSubjectTypeS.setSelectedIndex(0);
                        jcSem.setSelectedIndex(0);
                        jcSubjectTypeS.setSelectedIndex(0);
                        JcShiftS.setSelectedIndex(0);
                        jcYearS.insertItemAt("", 0);

                        DefaultListModel listmodel = (DefaultListModel) lstSubject.getModel();
                        listmodel.removeAllElements();
                        jcYearC.setSelectedIndex(0);
                        jcYearS.setSelectedIndex(0);

                        allSubject = new ArrayList<>();
                        v = new Vector();

                    } else {
                        JOptionPane.showMessageDialog(null, "Incorrect Password");
                    }
                    con.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Username is Present !!!");
            }
        } else if (index == 2) {
            try {
                String pass = new String(txtPasswordC.getPassword());
                String rePass = new String(txtRePasswordC.getPassword());
                String userName = txtUsernameC.getText();

                String Dept = (String) jcDepartmentC.getSelectedItem();
                String shift = (String) jcShiftC.getSelectedItem();
                String year = (String) jcYearC.getSelectedItem();
                if (pass.equals("") || rePass.equals("") || userName.equals("") || jcDepartmentC.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Please select All Field");
                } else {
                    con = dc.getConnection();
                    ps = con.prepareStatement("insert into class_teacher values(?,?,?,?,?)");

                    if (pass.equals(rePass)) {
                        ps.setString(1, userName);
                        ps.setString(2, pass);
                        ps.setString(3, Dept);
                        ps.setString(4, year);
                        ps.setString(5, shift);

                        ps.execute();
                        JOptionPane.showMessageDialog(null, "Account Created Successfully !!!");
                        txtPasswordC.setText("");
                        txtPasswordH.setText("");
                        txtPasswordS.setText("");
                        txtRePasswordC.setText("");
                        txtRePasswordH.setText("");
                        txtRePasswordS.setText("");
//                        txtSubjectS.setText("");
                        txtUserNameH.setText("");
                        txtUsernameC.setText("");
                        txtUsernameS.setText("");
                        JcShiftS.setSelectedIndex(0);
                        jcDepartmentC.setSelectedIndex(0);
                        jcDepartmentH.setSelectedIndex(0);
                        jcDepartmentS.setSelectedIndex(0);
                        jcShiftC.setSelectedIndex(0);
                        jcSubjectTypeS.setSelectedIndex(0);
//                    jcType.setSelectedIndex(0);
                        jcYearC.setSelectedIndex(0);
                        jcYearS.setSelectedIndex(0);
                       
                    } else {
                        JOptionPane.showMessageDialog(null, "Incorrect Password !!!");
                    }
                    con.close();
                }
            } catch (IllegalArgumentException ee) {
                   
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Username is Already Present !!!");    
            }
        } else if (index == 3) {
            try {
                String pass = new String(txtPasswordH.getPassword());
                String rePass = new String(txtRePasswordH.getPassword());
                String userName = txtUserNameH.getText();

                String Dept = (String) jcDepartmentH.getSelectedItem();
                if (pass.equals("") || rePass.equals("") || userName.equals("") || jcDepartmentH.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(null, "Please Enter All the Field !!!");
                } else {
                    con = dc.getConnection();
                    ps = con.prepareStatement("insert into hod values(?,?,?)");
                    if (pass.equals(rePass)) {
                        ps.setString(1, userName);
                        ps.setString(2, pass);
                        ps.setString(3, Dept);

                        ps.execute();
                        JOptionPane.showMessageDialog(null, "Account Created Successfully !!!");
                        txtPasswordC.setText("");
                        txtPasswordH.setText("");
                        txtPasswordS.setText("");
                        txtRePasswordC.setText("");
                        txtRePasswordH.setText("");
                        txtRePasswordS.setText("");
//                    txtSubjectS.setText("");
                        txtUserNameH.setText("");
                        txtUsernameC.setText("");
                        txtUsernameS.setText("");
                        JcShiftS.setSelectedIndex(0);
                        jcDepartmentC.setSelectedIndex(0);
                        jcDepartmentH.setSelectedIndex(0);
                        jcDepartmentS.setSelectedIndex(0);
                        jcShiftC.setSelectedIndex(0);
                        jcSubjectTypeS.setSelectedIndex(0);
//                    jcType.setSelectedIndex(0);
                        jcYearC.setSelectedIndex(0);
                        jcYearS.setSelectedIndex(0);
                    } else {
                        JOptionPane.showMessageDialog(null, "Incorrect Password !!!");
                    }
                    con.close();
                }
            } catch (IllegalArgumentException ee) {      
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Username is Already Present !!!");    
            }
        }
    }//GEN-LAST:event_BtnRegisterActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        MainPln.PnelMn.removeAll();
        MainPln.PnelMn.add(new Login(frm));
        MainPln.PnelMn.updateUI();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            txtPasswordC.setText("");
            txtPasswordH.setText("");
            txtPasswordS.setText("");
            txtRePasswordC.setText("");
            txtRePasswordH.setText("");
            txtRePasswordS.setText("");
            txtUserNameH.setText("");
            txtUsernameC.setText("");
            txtUsernameS.setText("");

            jcDepartmentC.setSelectedIndex(0);
            jcDepartmentH.setSelectedIndex(0);
            jcDepartmentS.setSelectedIndex(0);
            jcShiftC.setSelectedIndex(0);
            jcSubjectTypeS.setSelectedIndex(0);
            jcSem.setSelectedIndex(0);
            jcSubjectTypeS.setSelectedIndex(0);
            JcShiftS.setSelectedIndex(0);
            jcYearS.insertItemAt("", 0);
            DefaultListModel listmodel = (DefaultListModel) lstSubject.getModel();
            listmodel.removeAllElements();
            jcYearC.setSelectedIndex(0);
            jcYearS.setSelectedIndex(0);
            allSubject = new ArrayList<>();
            v = new Vector();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void JcShiftSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcShiftSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcShiftSActionPerformed
    Vector v = new Vector();

    private void jcSemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcSemActionPerformed
        // TODO add your handling code here:

        if (!(jcSem.getSelectedIndex() == 0) && !(jcDepartmentS.getSelectedIndex() == 0)) {
            List selectedValuesList = lstSubject.getSelectedValuesList();
            v.addAll(selectedValuesList);
            System.out.println("sub list ***  " + v);
            listModel.clear();
            jcYearS.removeAllItems();

            try {
                PreparedStatement ps = con11.prepareStatement("SELECT dept_name, semister_name, sub_name FROM student.subjects, student.semister, student.department where student.department.dept_id=student.subjects.dept_id and student.semister.semister_id= student.subjects.semister_id and student.department.dept_id=" + jcDepartmentS.getSelectedIndex() + " and semister.semister_id=" + jcSem.getSelectedIndex());
                ResultSet set = ps.executeQuery();
                while (set.next()) {
                    listModel.addElement(set.getString("sub_name"));
                }
                lstSubject.setModel(listModel);
                lstSubject.updateUI();
                if (jcSem.getSelectedIndex() == 1 || jcSem.getSelectedIndex() == 2) {
                    jcYearS.addItem("FY");
                } else if (jcSem.getSelectedIndex() == 3 || jcSem.getSelectedIndex() == 4) {
                    jcYearS.addItem("SY");
                } else if (jcSem.getSelectedIndex() == 5 || jcSem.getSelectedIndex() == 6) {
                    jcYearS.addItem("TY");
                }
                jcYearS.updateUI();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
//            JOptionPane.showMessageDialog(null, "Please Select Department or Semister  !!!");
        }
//        }
    }//GEN-LAST:event_jcSemActionPerformed

    private void lstSubjectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstSubjectKeyPressed

    }//GEN-LAST:event_lstSubjectKeyPressed

    private void lstSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstSubjectMouseClicked
        List selectedValuesList = lstSubject.getSelectedValuesList();
        for (int i = 0; i < selectedValuesList.size(); i++) {
            String get = selectedValuesList.get(i).toString();
            if (!allSubject.contains(get)) {
                allSubject.add(get);
            }
        }

//        System.out.println("allSubject :" + allSubject);
    }//GEN-LAST:event_lstSubjectMouseClicked
    private void createTable(String tbName) {
        try {
            con = dc.getConnection();
            String sqlCreate = "CREATE TABLE IF NOT EXISTS " + tbName
                    + "  (username           VARCHAR(100),"
                    + "   password            VARCHAR(100),"
                    + "   department          VARCHAR(100),"
                    + "   year            VARCHAR(100),"
                    + "   shift            VARCHAR(100),"
                    + "   subject            VARCHAR(100),"
                    + "   type            VARCHAR(100)," + "PRIMARY KEY (username))";

            PreparedStatement stmt = con.prepareStatement(sqlCreate);
            stmt.executeUpdate();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void createTable5(String tbName) {
        try {
            con = dc.getConnection();
            String sqlCreate = "CREATE TABLE IF NOT EXISTS " + tbName
                    + "  (username   VARCHAR(100),subject   VARCHAR(100),"
                    + "PRIMARY KEY (subject))";

            PreparedStatement stmt = con.prepareStatement(sqlCreate);
            stmt.executeUpdate();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void createTable1(String tbName) {
        try {
            con = dc.getConnection();
            String sqlCreate = "CREATE TABLE IF NOT EXISTS " + tbName
                    + "  (username           VARCHAR(100),"
                    + "   password            VARCHAR(100),"
                    + "   department          VARCHAR(100),"
                    + "   year            VARCHAR(100),"
                    + "   shift            VARCHAR(100)"
                    + ")";

            PreparedStatement stmt = con.prepareStatement(sqlCreate);
            stmt.executeUpdate();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void createTable2(String tbName) {
        try {
            con = dc.getConnection();
            String sqlCreate = "CREATE TABLE IF NOT EXISTS " + tbName
                    + "  (username           VARCHAR(100),"
                    + "   password            VARCHAR(100),"
                    + "   department          VARCHAR(100)"
                    + ")";

            PreparedStatement stmt = con.prepareStatement(sqlCreate);
            stmt.executeUpdate();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnRegister;
    private javax.swing.JPanel HODpnl;
    private javax.swing.JComboBox JcShiftS;
    private javax.swing.JPanel PnlClass;
    private javax.swing.JPanel PnlSubject;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcDepartmentC;
    private javax.swing.JComboBox jcDepartmentH;
    private javax.swing.JComboBox jcDepartmentS;
    private javax.swing.JComboBox jcSem;
    private javax.swing.JComboBox jcShiftC;
    private javax.swing.JComboBox jcSubjectTypeS;
    private javax.swing.JComboBox jcType;
    private javax.swing.JComboBox jcYearC;
    private javax.swing.JComboBox jcYearS;
    private javax.swing.JList lstSubject;
    private javax.swing.JPanel pnlHomePnl;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPasswordField txtPasswordC;
    private javax.swing.JPasswordField txtPasswordH;
    private javax.swing.JPasswordField txtPasswordS;
    private javax.swing.JPasswordField txtRePasswordC;
    private javax.swing.JPasswordField txtRePasswordH;
    private javax.swing.JPasswordField txtRePasswordS;
    private javax.swing.JTextField txtUserNameH;
    private javax.swing.JTextField txtUsernameC;
    private javax.swing.JTextField txtUsernameS;
    // End of variables declaration//GEN-END:variables
}
