package gui;

import dao.DaoConnection;
import java.awt.Frame;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Student_Registration extends javax.swing.JPanel {

    Frame frm;
    DaoConnection dc = new DaoConnection();
    Connection conn;

    public Student_Registration(Frame frm) {
        this.frm = frm;
        initComponents();
        conn = dc.getConnection();
        frm.setExtendedState(MAXIMIZED_BOTH);
        if (Login.isStatus.equalsIgnoreCase("Student Edit")) {
            try {
                String enro = JOptionPane.showInputDialog("Please Enter Enrollment");

                System.out.println("name ::: " + enro);
                while (enro.equals("")) {
                    JOptionPane.showMessageDialog(null, "Enter Edit Fields !!!", "Error", JOptionPane.ERROR_MESSAGE);
                    enro = JOptionPane.showInputDialog("Please Enter Firstname & Lastname !!!");
                }

//                if (!enro.equalsIgnoreCase("")) {
                PreparedStatement ps = conn.prepareStatement("Select * from registrationtbl where enroll='" + enro + "'");
                ResultSet set = ps.executeQuery();
                if (set.next()) {
                    txtEnroll.setText(set.getString("enroll"));
                    txtlast.setText(set.getString("last"));
                    tfname.setText(set.getString("name"));
                    tfcontact.setText(set.getString("contact"));
                    tfRoll.setText(set.getString("roll"));
                    String dd = set.getString("dob");
                    DateFormat format = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
                    Date date = format.parse(dd);

//                        Date d = new Date();
                    jXDatePickerDOB.setDate(date);
                    jcYear.setSelectedItem(set.getString("year"));
                    cbDepartment.setSelectedItem(set.getString("department"));
                    cbShift.setSelectedItem(set.getString("shift"));
                    InputStream binaryStream = set.getBinaryStream("photo");
                    String string = set.getString("gender");
                    if (string.equalsIgnoreCase("male")) {
                        rbMale.setSelected(true);
                        rbFemale.setSelected(false);
                    } else {
                        rbMale.setSelected(false);
                        rbFemale.setSelected(true);
                    }
                    File f = new File(System.getProperty("user.dir") + File.separator + "temp" + File.separator + "user.jpg");
//                        InputStream binaryStream = userimage.getBinaryStream(1, userimage.length());
                    FileOutputStream fos = new FileOutputStream(f);
                    int c = 0;
                    while ((c = binaryStream.read()) != -1) {
                        fos.write(c);
                    }
                    fos.close();
                    BufferedImage image = ImageIO.read(f);//108,124
                    image = linearResizeBi(image, 108, 124);
                    JLabel lblImg = new JLabel();
                    ImageIcon img = new ImageIcon(image);
                    lblImg.setIcon(img);
                    pnlPhoto.add(lblImg);
                    tfPhotoBrowse.setText(f.getAbsolutePath());
                    taAddress.setText(set.getString("address"));
                    txtEnroll.setEditable(false);
                } else {
                    JOptionPane.showMessageDialog(null, "No Record Found !!! ");
                    this.removeAll();;
                    this.add(new Login(frm));
                    this.updateUI();
                }
                conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jcYear = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfPhotoBrowse = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        cbShift = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        pnlPhoto = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfcontact = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        tfRoll = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbDepartment = new javax.swing.JComboBox();
        jXDatePickerDOB = new org.jdesktop.swingx.JXDatePicker();
        txtlast = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtEnroll = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jcBloodgroup = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMaximumSize(new java.awt.Dimension(464, 648));
        jPanel6.setMinimumSize(new java.awt.Dimension(464, 648));
        jPanel6.setPreferredSize(new java.awt.Dimension(464, 648));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(26, 42, 57));
        jPanel1.setMaximumSize(new java.awt.Dimension(839, 670));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Year");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 139, 0, 0);
        jPanel1.add(jLabel10, gridBagConstraints);

        jcYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FY", "SY", "TY" }));
        jcYear.setMinimumSize(new java.awt.Dimension(62, 24));
        jcYear.setPreferredSize(new java.awt.Dimension(62, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 139, 0, 0);
        jPanel1.add(jcYear, gridBagConstraints);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 139, 0, 0);
        jPanel1.add(jLabel15, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Photo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 139, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        tfPhotoBrowse.setEditable(false);
        tfPhotoBrowse.setMaximumSize(new java.awt.Dimension(6, 24));
        tfPhotoBrowse.setPreferredSize(new java.awt.Dimension(6, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 139, 0, 0);
        jPanel1.add(tfPhotoBrowse, gridBagConstraints);

        btnRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(26, 42, 57));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 169;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 139, 0, 0);
        jPanel1.add(btnRegister, gridBagConstraints);

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(26, 42, 57));
        btnReset.setText("Reset");
        btnReset.setMaximumSize(new java.awt.Dimension(110, 25));
        btnReset.setMinimumSize(new java.awt.Dimension(110, 25));
        btnReset.setPreferredSize(new java.awt.Dimension(110, 25));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 139, 0, 0);
        jPanel1.add(btnReset, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(26, 42, 57));
        jButton2.setText("Back");
        jButton2.setMaximumSize(new java.awt.Dimension(100, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(110, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(110, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 66, 210);
        jPanel1.add(jButton2, gridBagConstraints);

        btnBrowse.setBackground(new java.awt.Color(255, 255, 255));
        btnBrowse.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnBrowse.setForeground(new java.awt.Color(26, 42, 57));
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 139, 0, 0);
        jPanel1.add(btnBrowse, gridBagConstraints);

        jPanel8.setLayout(new java.awt.BorderLayout());

        taAddress.setColumns(20);
        taAddress.setLineWrap(true);
        taAddress.setRows(5);
        taAddress.setPreferredSize(new java.awt.Dimension(107, 94));
        jScrollPane1.setViewportView(taAddress);

        jPanel8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 233;
        gridBagConstraints.ipady = 73;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 139, 0, 0);
        jPanel1.add(jPanel8, gridBagConstraints);

        cbShift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II" }));
        cbShift.setPreferredSize(new java.awt.Dimension(70, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 223;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 139, 0, 0);
        jPanel1.add(cbShift, gridBagConstraints);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Shift");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(96, 139, 0, 0);
        jPanel1.add(jLabel11, gridBagConstraints);

        jPanel9.setMinimumSize(new java.awt.Dimension(7, 7));
        jPanel9.setLayout(new java.awt.BorderLayout());

        pnlPhoto.setBackground(new java.awt.Color(255, 255, 255));
        pnlPhoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPhoto.setMaximumSize(new java.awt.Dimension(4, 4));
        pnlPhoto.setPreferredSize(new java.awt.Dimension(4, 4));
        pnlPhoto.setLayout(new java.awt.BorderLayout());
        jPanel9.add(pnlPhoto, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 111;
        gridBagConstraints.ipady = 126;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 18, 0, 0);
        jPanel1.add(jPanel9, gridBagConstraints);

        jPanel6.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(26, 42, 57));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setMaximumSize(new java.awt.Dimension(464, 648));
        jPanel4.setPreferredSize(new java.awt.Dimension(464, 648));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 91, 0, 0);
        jPanel4.add(jLabel4, gridBagConstraints);

        tfname.setCaretColor(new java.awt.Color(0, 102, 102));
        tfname.setMinimumSize(new java.awt.Dimension(40, 24));
        tfname.setPreferredSize(new java.awt.Dimension(40, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 54;
        gridBagConstraints.ipadx = 217;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 91, 0, 120);
        jPanel4.add(tfname, gridBagConstraints);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact No. :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 91, 0, 0);
        jPanel4.add(jLabel6, gridBagConstraints);

        tfcontact.setCaretColor(new java.awt.Color(0, 102, 102));
        tfcontact.setMinimumSize(new java.awt.Dimension(40, 24));
        tfcontact.setPreferredSize(new java.awt.Dimension(40, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 54;
        gridBagConstraints.ipadx = 217;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 91, 0, 120);
        jPanel4.add(tfcontact, gridBagConstraints);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Date of Birth :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 91, 0, 0);
        jPanel4.add(jLabel17, gridBagConstraints);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 91, 0, 0);
        jPanel4.add(jLabel8, gridBagConstraints);

        rbMale.setBackground(new java.awt.Color(26, 42, 57));
        rbMale.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        rbMale.setForeground(new java.awt.Color(255, 255, 255));
        rbMale.setText("Male");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel4.add(rbMale, gridBagConstraints);

        rbFemale.setBackground(new java.awt.Color(26, 42, 57));
        rbFemale.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        rbFemale.setForeground(new java.awt.Color(255, 255, 255));
        rbFemale.setText("Female");
        rbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemaleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 2, 0, 0);
        jPanel4.add(rbFemale, gridBagConstraints);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Roll No. :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 91, 0, 0);
        jPanel4.add(jLabel16, gridBagConstraints);

        tfRoll.setCaretColor(new java.awt.Color(0, 102, 102));
        tfRoll.setMinimumSize(new java.awt.Dimension(40, 24));
        tfRoll.setPreferredSize(new java.awt.Dimension(40, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 53;
        gridBagConstraints.ipadx = 213;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 91, 0, 0);
        jPanel4.add(tfRoll, gridBagConstraints);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Department :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 91, 0, 0);
        jPanel4.add(jLabel14, gridBagConstraints);

        cbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ME", "Civil", "EJ", "CO", "IF" }));
        cbDepartment.setMinimumSize(new java.awt.Dimension(200, 27));
        cbDepartment.setPreferredSize(new java.awt.Dimension(200, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 35;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -75;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 13, 70, 0);
        jPanel4.add(cbDepartment, gridBagConstraints);

        jXDatePickerDOB.setBackground(new java.awt.Color(154, 204, 255));
        jXDatePickerDOB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jXDatePickerDOB.setMinimumSize(new java.awt.Dimension(140, 26));
        jXDatePickerDOB.setPreferredSize(new java.awt.Dimension(140, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 34;
        gridBagConstraints.ipadx = 109;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 91, 0, 0);
        jPanel4.add(jXDatePickerDOB, gridBagConstraints);

        txtlast.setMinimumSize(new java.awt.Dimension(40, 24));
        txtlast.setPreferredSize(new java.awt.Dimension(40, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 54;
        gridBagConstraints.ipadx = 217;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 91, 0, 120);
        jPanel4.add(txtlast, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Last Name :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 91, 0, 0);
        jPanel4.add(jLabel9, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Enrollment No : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(80, 91, 0, 0);
        jPanel4.add(jLabel18, gridBagConstraints);

        txtEnroll.setMinimumSize(new java.awt.Dimension(40, 24));
        txtEnroll.setPreferredSize(new java.awt.Dimension(40, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 54;
        gridBagConstraints.ipadx = 217;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 91, 0, 120);
        jPanel4.add(txtEnroll, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Blood Group :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 91, 0, 0);
        jPanel4.add(jLabel12, gridBagConstraints);

        jcBloodgroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        jcBloodgroup.setMaximumSize(new java.awt.Dimension(56, 18));
        jcBloodgroup.setMinimumSize(new java.awt.Dimension(56, 18));
        jcBloodgroup.setPreferredSize(new java.awt.Dimension(56, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 13, 0, 0);
        jPanel4.add(jcBloodgroup, gridBagConstraints);

        jPanel5.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(26, 42, 57));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setPreferredSize(new java.awt.Dimension(861, 92));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("M.I.T. Polytechnic,Pune");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 331, 0, 0);
        jPanel7.add(jLabel3, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MIT College Road,Rambaugh Colony,Kothrud,Pune,Maharashtra");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 230, 0, 230);
        jPanel7.add(jLabel5, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("sspp@mitsspp.edu.in     Contact no. 020-30273531");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 294, 0, 0);
        jPanel7.add(jLabel7, gridBagConstraints);

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        if (rbMale.isSelected()) {
            rbFemale.setSelected(false);
        }
    }//GEN-LAST:event_rbMaleActionPerformed

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        if (rbFemale.isSelected()) {
            rbMale.setSelected(false);
        }
    }//GEN-LAST:event_rbFemaleActionPerformed

    private BufferedImage linearResizeBi(BufferedImage origin, int width, int height) {
        BufferedImage resizedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = resizedImage.createGraphics();
        float xScale = (float) width / origin.getWidth();
        float yScale = (float) height / origin.getHeight();
        AffineTransform at = AffineTransform.getScaleInstance(xScale, yScale);
        g.drawRenderedImage(origin, at);
        g.dispose();
        return resizedImage;
    }

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
//        Connection conn = null;
        DaoConnection dao = new DaoConnection();

        if (("".equals(tfname.getText())) || ("".equals(tfcontact.getText())) || ("".equals(taAddress.getText())) || ("".equals(tfRoll.getText()))) {
            JOptionPane.showMessageDialog(null, "Please Enter all the Fields !!!");
        } else {
//            String emailregex = "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
//            Boolean checkEmail = mailtxt.getText().trim().matches(emailregex);

            Pattern pattern = Pattern.compile("\\d{10}");
            Matcher matcherMobile = pattern.matcher(tfcontact.getText());
            Matcher matcherEnroll = pattern.matcher(txtEnroll.getText());

            Pattern pattern1 = Pattern.compile("^[a-zA-Z]+([\\s][a-zA-Z]+)*$");
            Matcher matcherFName = pattern1.matcher(tfname.getText().trim());

            Pattern pattern2 = Pattern.compile("^[0-9]+([\\s][0-9]+)*$");
            Matcher matcherRoll = pattern2.matcher(tfRoll.getText().trim());

            if (!matcherMobile.matches()) {
                JOptionPane.showMessageDialog(null, "Enter Valid Mobile Nuumber !!!");
            } else if (!matcherFName.matches()) {
                JOptionPane.showMessageDialog(null, "Enter Valid First Name !!!");
            } else if (!matcherRoll.matches()) {
                JOptionPane.showMessageDialog(null, "Enter Valid Roll number !!!");
//            } else if (!matcherEnroll.matches()) {
//                JOptionPane.showMessageDialog(null, "Enter Valid 10 Digit Enrollment number !!!");
            } else {

                FileInputStream input = null;
                try {
                    int x = 0;
                    String enroll = txtEnroll.getText();
                    String s1 = tfname.getText();
                    String s2 = tfcontact.getText();
                    Date s3 = jXDatePickerDOB.getDate();
                    String last = txtlast.getText();
                    String s4 = tfRoll.getText();
                    String s5 = (String) cbDepartment.getSelectedItem();
                    String s6 = (String) cbShift.getSelectedItem();
                    String s7 = taAddress.getText();
                    String s8 = tfPhotoBrowse.getText();
                    input = new FileInputStream(s8);
                    String s9 = (String) jcBloodgroup.getSelectedItem();
                    String year = (String) jcYear.getSelectedItem();
                    String status = "";
                    boolean selected = rbFemale.isSelected();
                    if (selected) {
                        status = "Female";
                    } else {
                        status = "Male";
                    }

//                    FileInputStream input1 = new FileInputStream(s9);
                    SimpleDateFormat dt = new SimpleDateFormat("dd-MM-yyyy");
                    String s10 = dt.format(s3);

                    System.out.println(s1);
                    System.out.println(s2);
                    System.out.println(s3);
                    System.out.println(s4);
                    System.out.println(s5);
                    System.out.println(s6);
                    System.out.println(s7);
                    System.out.println(s10);
                    System.out.println(s9);
                    String first = s1.substring(0, 1).toUpperCase() + s1.substring(1);
                    String lastname = last.substring(0, 1).toUpperCase() + last.substring(1);
                    String address = s7.substring(0, 1).toUpperCase() + s7.substring(1);

                    try {
                        conn = dao.getConnection();
                        PreparedStatement ps;
                        if (Login.isStatus.equalsIgnoreCase("Student Edit")) {
                            ps = conn.prepareStatement("update registrationtbl set enroll=?,name=?,last=?,contact=?,dob=?,gender=?,roll=?,department=?,shift=?,year=?,address=?,photo=?,bloodgroup=? where enroll='" + enroll + "'");
                        } else {
                            ps = conn.prepareStatement("insert into registrationtbl (enroll,name,last,contact,dob,gender,roll,department,shift,year,address,photo,bloodgroup)" + (" values(?,?,?,?,?,?,?,?,?,?,?,?,?)"));

                        }
                        ps.setString(1, enroll);
                        ps.setString(2, first);
                        ps.setString(3, lastname);
                        ps.setString(4, s2);

                        ps.setString(5, s10);
                        ps.setString(6, status);
                        ps.setString(7, s4);
                        ps.setString(8, s5);
                        ps.setString(9, s6);
                        ps.setString(10, year);
                        ps.setString(11, address);
                        ps.setBlob(12, input);
                        ps.setString(13, s9);
                        ps.executeUpdate();
                        conn.close();
                        x++;
                        if (x > 0) {
                            if (Login.isStatus.equalsIgnoreCase("Edit")) {
                                JOptionPane.showMessageDialog(null, "Account Updated Successfully");
                            } else {
                                JOptionPane.showMessageDialog(null, "Account Created Successfully");
                            }
                            taAddress.setFocusable(false);
                            tfPhotoBrowse.setText("");
                            tfRoll.setText("");
//                            tfSignBrowse.setText("");
                            tfcontact.setText("");
                            txtlast.setText("");
                            tfname.setText("");
                            txtEnroll.setText("");
                            cbDepartment.setSelectedIndex(0);
                            jcBloodgroup.setSelectedIndex(0);
                            cbShift.setSelectedIndex(0);
                            jcYear.setSelectedIndex(0);
                            taAddress.setText("");
                            rbFemale.setSelected(false);
                            rbMale.setSelected(false);
//                            jXDatePickerDOB.removeAll();
                            jXDatePickerDOB.setDate(null);
                            this.jXDatePickerDOB.updateUI();
                            this.pnlPhoto.removeAll();
//                            this.pnlSign.removeAll();
                            this.pnlPhoto.updateUI();
//                            this.pnlSign.updateUI();
                            this.updateUI();
                            txtEnroll.setRequestFocusEnabled(true);
                            txtEnroll.setFocusable(true);
                            taAddress.setFocusable(true);
                            tfcontact.setFocusable(true);

                        }
                    } catch (SQLException | HeadlessException e) {
//                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Enrollment Number is Already Present !!!");
                    }
                } catch (FileNotFoundException ex) {

                } finally {
                    try {
                        input.close();
                    } catch (IOException ex) {

                    }
                }
            }
        }


    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        tfPhotoBrowse.setText("");
        tfRoll.setText("");
//        tfSignBrowse.setText("");
        tfcontact.setText("");
        tfname.setText("");
        txtEnroll.setText("");
        this.pnlPhoto.removeAll();
//        this.pnlSign.removeAll();
        this.pnlPhoto.updateUI();
//        this.pnlSign.updateUI();
        jXDatePickerDOB.removeAll();
        cbDepartment.setSelectedIndex(0);
        cbShift.setSelectedIndex(0);
        taAddress.setText("");
        JOptionPane.showMessageDialog(null, "Fields Cleared !!!");
    }//GEN-LAST:event_btnResetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MainPln.PnelMn.removeAll();
        //                            gui.MainPanel.add(new Student_Registration(gui));
        MainPln.PnelMn.add(new Login(frm));
        MainPln.PnelMn.updateUI();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        try {
            this.pnlPhoto.removeAll();
            JFileChooser chooser = new JFileChooser(System.getProperty("user.dir") + File.separator + "photo" + File.separator);
            chooser.showOpenDialog(null);

            File f = chooser.getSelectedFile();
            System.out.println("" + f);
            tfPhotoBrowse.setText(f.getAbsolutePath());

            BufferedImage image = ImageIO.read(f);//108,124
            image = linearResizeBi(image, 118, 134);
            JLabel lblImg = new JLabel();
            ImageIcon img = new ImageIcon(image);
            lblImg.setIcon(img);
            this.pnlPhoto.add(lblImg);
            this.pnlPhoto.updateUI();

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnReset;
    public javax.swing.JComboBox cbDepartment;
    public javax.swing.JComboBox cbShift;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public org.jdesktop.swingx.JXDatePicker jXDatePickerDOB;
    private javax.swing.JComboBox jcBloodgroup;
    private javax.swing.JComboBox jcYear;
    private javax.swing.JPanel pnlPhoto;
    public javax.swing.JRadioButton rbFemale;
    public javax.swing.JRadioButton rbMale;
    private javax.swing.JTextArea taAddress;
    public javax.swing.JTextField tfPhotoBrowse;
    public javax.swing.JTextField tfRoll;
    public javax.swing.JTextField tfcontact;
    public javax.swing.JTextField tfname;
    private javax.swing.JTextField txtEnroll;
    private javax.swing.JTextField txtlast;
    // End of variables declaration//GEN-END:variables
}
