/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DaoConnection;
import java.awt.Color;
import java.awt.Frame;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class TeacherReg1 extends javax.swing.JPanel {

    Frame frm;
    DaoConnection dc = new DaoConnection();
    Connection con;

    public TeacherReg1(Frame frm) {
        this.frm = frm;
        initComponents();
        con = dc.getConnection();
        frm.setExtendedState(MAXIMIZED_BOTH);
        try {

            if (Login.isStatus.equalsIgnoreCase("Teacher Edit")) {
                String name = JOptionPane.showInputDialog("Please Enter Firstname And Lastname !!!");
                System.out.println("name ::: " + name);
                while (name.equals("")) {
                    JOptionPane.showMessageDialog(null, "Enter Edit Fields !!!", "Error", JOptionPane.ERROR_MESSAGE);
                    name = JOptionPane.showInputDialog("Please Enter Firstname & Lastname !!!");
                }
                while (!name.contains(" ")) {
                    JOptionPane.showMessageDialog(null, "Enter Valid Firstname & Lastname !!!", "Error", JOptionPane.WARNING_MESSAGE);
                    name = JOptionPane.showInputDialog("Please Enter Firstname & Lastname !!!");
                }
                
                String[] split = name.split(" ");
                String fname = split[0];
                String lname = split[1];
                PreparedStatement ps = con.prepareStatement("select * from tbtecher where first='" + fname + "'&&last='" + lname + "'");
                ResultSet set = ps.executeQuery();
                if (set.next()) {
                    tfname.setText(set.getString("first"));
                    tfcontact.setText(set.getString("contact"));
                    tfdesignation.setText(set.getString("desig"));
                    txtAddress.setText(set.getString("address"));
                    txtlast.setText(set.getString("last"));
                    jcShift.setSelectedItem(set.getString("shift"));
                    cbDepartment.setSelectedItem(set.getString("dept"));
                    InputStream binaryStream = set.getBinaryStream("photo");
                    File f = new File(System.getProperty("user.dir") + File.separator + "temp" + File.separator + "user.jpg");
                    FileOutputStream fos = new FileOutputStream(f);
                    int c = 0;
                    while ((c = binaryStream.read()) != -1) {
                        fos.write(c);
                    }
                    fos.close();
                    BufferedImage image = ImageIO.read(f);//108,124
                    image = linearResizeBi(image, 108, 124);
                    JLabel lblImg = new JLabel();
                    ImageIcon img = new ImageIcon(image);
                    lblImg.setIcon(img);
                    pnlPhoto.add(lblImg);
                    tfPhotoBrowse.setText(f.getAbsolutePath());
                } else {
                    JOptionPane.showMessageDialog(null, "No Such Account !!!");
                    this.removeAll();
                    this.add(new Login(frm));
                    this.updateUI();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(TeacherReg1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TeacherReg1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TeacherReg1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tfname = new javax.swing.JTextField();
        txtlast = new javax.swing.JTextField();
        tfcontact = new javax.swing.JTextField();
        cbDepartment = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcShift = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        tfdesignation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pnlPhoto = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        tfPhotoBrowse = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(26, 42, 57));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        tfname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfname.setToolTipText("");
        tfname.setMaximumSize(new java.awt.Dimension(56, 10));
        tfname.setMinimumSize(new java.awt.Dimension(56, 10));
        tfname.setPreferredSize(new java.awt.Dimension(56, 10));
        tfname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfnameMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfnameMousePressed(evt);
            }
        });
        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });
        tfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfnameKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 159, 0, 0);
        jPanel3.add(tfname, gridBagConstraints);

        txtlast.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtlast.setMaximumSize(new java.awt.Dimension(56, 10));
        txtlast.setMinimumSize(new java.awt.Dimension(56, 10));
        txtlast.setPreferredSize(new java.awt.Dimension(56, 10));
        txtlast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlastMouseClicked(evt);
            }
        });
        txtlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastActionPerformed(evt);
            }
        });
        txtlast.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlastKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 159, 0, 0);
        jPanel3.add(txtlast, gridBagConstraints);

        tfcontact.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfcontact.setCaretColor(new java.awt.Color(0, 102, 102));
        tfcontact.setMaximumSize(new java.awt.Dimension(56, 15));
        tfcontact.setMinimumSize(new java.awt.Dimension(56, 15));
        tfcontact.setPreferredSize(new java.awt.Dimension(56, 15));
        tfcontact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfcontactMouseClicked(evt);
            }
        });
        tfcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfcontactKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 159, 0, 0);
        jPanel3.add(tfcontact, gridBagConstraints);

        cbDepartment.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbDepartment.setForeground(new java.awt.Color(153, 153, 153));
        cbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Department", "ME", "Civil", "E&TC", "CO", "IF" }));
        cbDepartment.setMaximumSize(new java.awt.Dimension(56, 20));
        cbDepartment.setMinimumSize(new java.awt.Dimension(56, 20));
        cbDepartment.setPreferredSize(new java.awt.Dimension(56, 20));
        cbDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDepartmentMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 178;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 159, 0, 0);
        jPanel3.add(cbDepartment, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(268, 159, 0, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 159, 0, 0);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact No.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 159, 0, 0);
        jPanel3.add(jLabel4, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 159, 0, 0);
        jPanel3.add(jLabel6, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Shift");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 159, 0, 0);
        jPanel3.add(jLabel8, gridBagConstraints);

        jcShift.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jcShift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 197;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 159, 0, 0);
        jPanel3.add(jcShift, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(26, 42, 57));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        tfdesignation.setCaretColor(new java.awt.Color(0, 102, 102));
        tfdesignation.setMaximumSize(new java.awt.Dimension(56, 15));
        tfdesignation.setMinimumSize(new java.awt.Dimension(56, 15));
        tfdesignation.setPreferredSize(new java.awt.Dimension(56, 15));
        tfdesignation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfdesignationMouseClicked(evt);
            }
        });
        tfdesignation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdesignationKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 193;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 179, 0, 0);
        jPanel4.add(tfdesignation, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Designation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 179, 0, 0);
        jPanel4.add(jLabel10, gridBagConstraints);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPhoto.setBackground(new java.awt.Color(255, 255, 255));
        pnlPhoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPhoto.setLayout(new java.awt.GridBagLayout());
        jPanel5.add(pnlPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 3, 140, 120));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 179, 0, 0);
        jPanel4.add(jPanel5, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(26, 42, 57));
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 177;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 179, 0, 20);
        jPanel4.add(jButton1, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 179, 0, 0);
        jPanel4.add(jLabel11, gridBagConstraints);

        jPanel6.setPreferredSize(new java.awt.Dimension(23, 9));
        jPanel6.setLayout(new java.awt.BorderLayout());

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtAddress.setLineWrap(true);
        txtAddress.setRows(5);
        txtAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAddress.setMaximumSize(new java.awt.Dimension(100, 50));
        txtAddress.setMinimumSize(new java.awt.Dimension(10, 50));
        txtAddress.setPreferredSize(new java.awt.Dimension(10, 50));
        jScrollPane1.setViewportView(txtAddress);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 231;
        gridBagConstraints.ipady = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 179, 11, 20);
        jPanel4.add(jPanel6, gridBagConstraints);

        tfPhotoBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhotoBrowseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 248;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 179, 0, 20);
        jPanel4.add(tfPhotoBrowse, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Photo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 179, 0, 0);
        jPanel4.add(jLabel12, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(196, 235, 226, 106);
        jPanel3.add(jPanel4, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(26, 42, 57));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("M.I.T. College Road, Rambaugh Colony, Kothrud, Pune, Maharashtra");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 211, 0, 212);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("M.I.T. Polytechnic,Pune");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 272, 0, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("sspp@mitsspp.edu.in     Contact no. 020-30273531");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 248, 10, 0);
        jPanel2.add(jLabel7, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(26, 42, 57));

        btnRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(26, 42, 57));
        btnRegister.setText("Register");
        btnRegister.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegister.setPreferredSize(new java.awt.Dimension(150, 40));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel7.add(btnRegister);

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(26, 42, 57));
        btnClear.setText("Reset");
        btnClear.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnClear.setPreferredSize(new java.awt.Dimension(150, 40));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel7.add(btnClear);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(26, 42, 57));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBack.setPreferredSize(new java.awt.Dimension(150, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel7.add(btnBack);

        add(jPanel7, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void tfnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfnameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameMousePressed

    private void tfnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfnameMouseClicked
//        tfname.setText("");
//        tfname.setForeground(Color.black);
    }//GEN-LAST:event_tfnameMouseClicked

    private void tfnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfnameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameMouseEntered

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    private void tfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnameKeyPressed
        // TODO add your handling code here:
        //        tfname.setText("");

    }//GEN-LAST:event_tfnameKeyPressed

    private void txtlastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlastMouseClicked

    }//GEN-LAST:event_txtlastMouseClicked

    private void txtlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastActionPerformed

    private void txtlastKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlastKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtlastKeyTyped

    private void tfcontactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfcontactMouseClicked

    }//GEN-LAST:event_tfcontactMouseClicked

    private void tfcontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcontactKeyTyped

    }//GEN-LAST:event_tfcontactKeyTyped

    private void cbDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDepartmentMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbDepartmentMouseClicked

    private void tfdesignationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfdesignationMouseClicked

    }//GEN-LAST:event_tfdesignationMouseClicked

    private void tfdesignationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdesignationKeyTyped

    }//GEN-LAST:event_tfdesignationKeyTyped

    private BufferedImage linearResizeBi(BufferedImage origin, int width, int height) {
        BufferedImage resizedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = resizedImage.createGraphics();
        float xScale = (float) width / origin.getWidth();
        float yScale = (float) height / origin.getHeight();
        AffineTransform at = AffineTransform.getScaleInstance(xScale, yScale);
        g.drawRenderedImage(origin, at);
        g.dispose();
        return resizedImage;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            pnlPhoto.removeAll();
            JFileChooser chooser = new JFileChooser(System.getProperty("user.dir") + File.separator + "photo" + File.separator);
            chooser.showOpenDialog(null);

            File f = chooser.getSelectedFile();
            System.out.println("" + f);
            tfPhotoBrowse.setText(f.getAbsolutePath());

            BufferedImage image = ImageIO.read(f);//108,124
            image = linearResizeBi(image, 108, 124);
            JLabel lblImg = new JLabel();
            ImageIcon img = new ImageIcon(image);
            lblImg.setIcon(img);
            this.pnlPhoto.add(lblImg);
            this.pnlPhoto.updateUI();

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        Connection conn = null;
        DaoConnection dao = new DaoConnection();

        if (("".equals(tfname.getText())) || ("".equals(tfcontact.getText())) || ("".equals(tfdesignation.getText())) || ("".equals(txtlast.getText())) || ("".equals(txtAddress.getText()))) {
            JOptionPane.showMessageDialog(null, "Please Enter all the Fields !!!");
        } else {
            //            String emailregex = "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
            //            Boolean checkEmail = mailtxt.getText().trim().matches(emailregex);

            Pattern pattern = Pattern.compile("\\d{10}");
            Matcher matcherMobile = pattern.matcher(tfcontact.getText());

            Pattern pattern1 = Pattern.compile("^[a-zA-Z]+([\\s][a-zA-Z]+)*$");
            Matcher matcherFName = pattern1.matcher(tfname.getText().trim());
            Matcher matcherLName = pattern1.matcher(txtlast.getText().trim());
            Matcher deg = pattern1.matcher(tfdesignation.getText().trim());

            //            Pattern pattern2 = Pattern.compile("^[0-9]+([\\s][0-9]+)*$");
            //            Matcher matcherRoll = pattern2.matcher(tfRoll.getText().trim());
            if (!matcherMobile.matches()) {
                JOptionPane.showMessageDialog(null, "Enter Valid Mobile Nuumber !!!");
            } else if (!matcherFName.matches()) {
                JOptionPane.showMessageDialog(null, "Enter Valid First Name !!!");
            } else if (!matcherLName.matches()) {
                JOptionPane.showMessageDialog(null, "Enter Valid Last Name !!!");
            } else if (!deg.matches()) {
                JOptionPane.showMessageDialog(null, "Enter Valid Designation !!!");
                //            } else if (!matcherRoll.matches()) {
                //                JOptionPane.showMessageDialog(null, "Enter Valid Roll number !!!");
            } else {

                FileInputStream input = null;
//                FileInputStream input1 = null;
                try {
                    int x = 0;;
                    String s1 = tfname.getText();
                    String s2 = tfcontact.getText();
                    String last = txtlast.getText();
                    String s5 = (String) cbDepartment.getSelectedItem();
                    String s8 = tfPhotoBrowse.getText();
                    input = new FileInputStream(s8);
                    String Addre = txtAddress.getText();
                    String desig = tfdesignation.getText();
                    String selectedItem = (String) jcShift.getSelectedItem();
//                    String pass = new String(txtPassword.getPassword());
//                    String rePass = new String(txtRePassword.getPassword());
//                    input1 = new FileInputStream(s9);
                    SimpleDateFormat dt = new SimpleDateFormat("dd-MM-yyyy");
                    //                    String s10 = dt.format(s3);

                    System.out.println(s1);
                    System.out.println(s2);
                    System.out.println(s5);
                    String first = s1.substring(0, 1).toUpperCase() + s1.substring(1);
                    String lastname = last.substring(0, 1).toUpperCase() + last.substring(1);

                    try {
                        conn = dao.getConnection();

                        PreparedStatement ps;
                        if (Login.isStatus.equalsIgnoreCase("Teacher Edit")) {
                            ps = conn.prepareStatement("update tbtecher set first=?,last=?,contact=?,dept=?,desig=?,photo=?,shift=?,address=? where first='" + first + "'&&last='" + lastname + "'");
                        } else {
                            ps = conn.prepareStatement("insert into  tbtecher (first,last,contact,dept,desig,photo,shift,address) values(?,?,?,?,?,?,?,?)");
                        }
                        if (cbDepartment.getSelectedIndex() == 0) {
                            JOptionPane.showMessageDialog(null, "Please Select Department...");
                        } else {
//                            if (pass.equals(rePass)) {

                            ps.setString(1, first);
                            ps.setString(2, lastname);
                            ps.setString(3, s2);

                            //                        ps.setString(5, s10);
                            ps.setString(4, s5);
                            ps.setString(5, desig);
                            //                        ps.setString(8, s5);
                            //                        ps.setString(9, s6);
                            //                        ps.setString(10, year);
                            //                        ps.setString(11, address);
                            ps.setBlob(6, input);
                            ps.setString(7, selectedItem);
                            ps.setString(8, Addre);
                            ps.executeUpdate();
                            //                    con.close();
                            x++;
//                            }
                        }
                        if (x > 0) {
                            JOptionPane.showMessageDialog(null, "Account Created Successfully !!!");
                            //                            taAddress.setFocusable(false);
                            tfPhotoBrowse.setText("Photo");
                            tfdesignation.setText("");
//                            tfSignBrowse.setText("Sign");
                            tfcontact.setText("");
                            txtlast.setText("");
                            tfname.setText("");
                            txtAddress.setText("");
//                            txtRePassword.setText("");
                            //                            txtEnroll.setText("");
                            tfPhotoBrowse.updateUI();
                            tfdesignation.updateUI();
//                            tfSignBrowse.updateUI();
                            tfcontact.updateUI();
                            tfname.updateUI();
                            txtlast.updateUI();
                            cbDepartment.setSelectedIndex(0);
                            //                            cbShift.setSelectedIndex(0);
                            //                            jcYear.setSelectedIndex(0);
                            //                            taAddress.setText("");
                            //                            rbFemale.setSelected(false);
                            //                            rbMale.setSelected(false);
                            //                            jXDatePickerDOB.removeAll();
                            //                            jXDatePickerDOB.setDate(null);
                            //                            this.jXDatePickerDOB.updateUI();
                            this.pnlPhoto.removeAll();
//                            this.pnlSign.removeAll();
                            this.pnlPhoto.updateUI();
//                            this.pnlSign.updateUI();
                            this.updateUI();
                            //                            txtEnroll.setRequestFocusEnabled(true);
                            //                            txtEnroll.setFocusable(true);
                            //                            taAddress.setFocusable(true);
                            tfcontact.setFocusable(true);

                        }
                    } catch (SQLException | HeadlessException e) {
                        System.out.println(e);
                    }
                } catch (FileNotFoundException ex) {

                } finally {
                    try {
//                        input1.close();
                        input.close();

                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfPhotoBrowse.setText("");
        txtlast.setText("");
//        tfSignBrowse.setText("");
        tfcontact.setText("");
        tfname.setText("");
        txtAddress.setText("");
//        txtRePassword.setText("");
        tfdesignation.setText("");
        //        txtEnroll.setText("");
        this.pnlPhoto.removeAll();
//        this.pnlSign.removeAll();
        this.pnlPhoto.updateUI();
//        this.pnlSign.updateUI();
        //        jXDatePickerDOB.removeAll();
        cbDepartment.setSelectedIndex(0);
        //        cbShift.setSelectedIndex(0);
        //        taAddress.setText("");
        JOptionPane.showMessageDialog(null, "Fields Cleared !!!");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainPln.PnelMn.removeAll();

        MainPln.PnelMn.add(new Login(frm));
        MainPln.PnelMn.updateUI();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tfPhotoBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhotoBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhotoBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRegister;
    public javax.swing.JComboBox cbDepartment;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcShift;
    private javax.swing.JPanel pnlPhoto;
    private javax.swing.JTextField tfPhotoBrowse;
    public javax.swing.JTextField tfcontact;
    public javax.swing.JTextField tfdesignation;
    public javax.swing.JTextField tfname;
    private javax.swing.JTextArea txtAddress;
    public javax.swing.JTextField txtlast;
    // End of variables declaration//GEN-END:variables
}
