/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.DaoConnection;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class Teacher_Registration extends javax.swing.JPanel {

    /**
     * Creates new form Registration
     */
//    GUI_MAIN gui;

    public Teacher_Registration() {
//        this.gui = gui;
        initComponents();
//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        gui.setLocation(screenSize.width / 2 - gui.getSize().width / 2, screenSize.height / 2 - gui.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tfname = new javax.swing.JTextField();
        tfcontact = new javax.swing.JTextField();
        cbDepartment = new javax.swing.JComboBox();
        txtlast = new javax.swing.JTextField();
        tfdesignation = new javax.swing.JTextField();
        tfPhotoBrowse = new javax.swing.JTextField();
        tfSignBrowse = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlPhoto = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        pnlSign = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(5, 69, 134));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(321, 512));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        tfname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfname.setForeground(new java.awt.Color(153, 153, 153));
        tfname.setText("First Name");
        tfname.setToolTipText("");
        tfname.setMaximumSize(new java.awt.Dimension(56, 20));
        tfname.setMinimumSize(new java.awt.Dimension(56, 20));
        tfname.setPreferredSize(new java.awt.Dimension(56, 20));
        tfname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfnameMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfnameMousePressed(evt);
            }
        });
        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });
        tfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfnameKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 135;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 301, 0, 0);
        jPanel4.add(tfname, gridBagConstraints);

        tfcontact.setForeground(new java.awt.Color(153, 153, 153));
        tfcontact.setText("Contact No.");
        tfcontact.setCaretColor(new java.awt.Color(0, 102, 102));
        tfcontact.setMaximumSize(new java.awt.Dimension(56, 20));
        tfcontact.setMinimumSize(new java.awt.Dimension(56, 20));
        tfcontact.setPreferredSize(new java.awt.Dimension(56, 20));
        tfcontact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfcontactMouseClicked(evt);
            }
        });
        tfcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfcontactKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.ipadx = 344;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 301, 0, 0);
        jPanel4.add(tfcontact, gridBagConstraints);

        cbDepartment.setForeground(new java.awt.Color(153, 153, 153));
        cbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DepartMent", "Mechnical", "Civil", "E & TC", "Computer", "Information Technology" }));
        cbDepartment.setMaximumSize(new java.awt.Dimension(56, 20));
        cbDepartment.setMinimumSize(new java.awt.Dimension(56, 20));
        cbDepartment.setPreferredSize(new java.awt.Dimension(56, 20));
        cbDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDepartmentMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.ipadx = 344;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 301, 0, 0);
        jPanel4.add(cbDepartment, gridBagConstraints);

        txtlast.setForeground(new java.awt.Color(153, 153, 153));
        txtlast.setText("Last Name");
        txtlast.setMaximumSize(new java.awt.Dimension(56, 20));
        txtlast.setMinimumSize(new java.awt.Dimension(56, 20));
        txtlast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlastMouseClicked(evt);
            }
        });
        txtlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastActionPerformed(evt);
            }
        });
        txtlast.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlastKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 19, 0, 0);
        jPanel4.add(txtlast, gridBagConstraints);

        tfdesignation.setForeground(new java.awt.Color(153, 153, 153));
        tfdesignation.setText("Designation");
        tfdesignation.setCaretColor(new java.awt.Color(0, 102, 102));
        tfdesignation.setMaximumSize(new java.awt.Dimension(56, 20));
        tfdesignation.setMinimumSize(new java.awt.Dimension(56, 20));
        tfdesignation.setPreferredSize(new java.awt.Dimension(56, 20));
        tfdesignation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfdesignationMouseClicked(evt);
            }
        });
        tfdesignation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdesignationKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.ipadx = 344;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 301, 0, 0);
        jPanel4.add(tfdesignation, gridBagConstraints);

        tfPhotoBrowse.setEditable(false);
        tfPhotoBrowse.setBackground(new java.awt.Color(255, 255, 255));
        tfPhotoBrowse.setForeground(new java.awt.Color(153, 153, 153));
        tfPhotoBrowse.setText("Photo");
        tfPhotoBrowse.setMaximumSize(new java.awt.Dimension(6, 24));
        tfPhotoBrowse.setPreferredSize(new java.awt.Dimension(6, 24));
        tfPhotoBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhotoBrowseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 181;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 301, 0, 0);
        jPanel4.add(tfPhotoBrowse, gridBagConstraints);

        tfSignBrowse.setEditable(false);
        tfSignBrowse.setBackground(new java.awt.Color(255, 255, 255));
        tfSignBrowse.setForeground(new java.awt.Color(153, 153, 153));
        tfSignBrowse.setText("Sign");
        tfSignBrowse.setMaximumSize(new java.awt.Dimension(6, 24));
        tfSignBrowse.setPreferredSize(new java.awt.Dimension(6, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 181;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 301, 0, 0);
        jPanel4.add(tfSignBrowse, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 114;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 301, 0, 0);
        jPanel4.add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.ipadx = 116;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 301, 0, 0);
        jPanel4.add(jButton2, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Teacher's Registration Form");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 301, 0, 0);
        jPanel4.add(jLabel1, gridBagConstraints);

        btnRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(102, 0, 51));
        btnRegister.setText("Register");
        btnRegister.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 301, 36, 0);
        jPanel4.add(btnRegister, gridBagConstraints);

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(102, 0, 51));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 19, 36, 0);
        jPanel4.add(btnClear, gridBagConstraints);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 0, 51));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 44;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 4, 36, 288);
        jPanel4.add(btnBack, gridBagConstraints);

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(102, 0, 51));
        btnClose.setText("Close");
        btnClose.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 18, 36, 0);
        jPanel4.add(btnClose, gridBagConstraints);

        pnlPhoto.setBackground(new java.awt.Color(255, 255, 255));
        pnlPhoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPhoto.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 30;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 74, 0, 0);
        jPanel4.add(jPanel1, gridBagConstraints);

        pnlSign.setBackground(new java.awt.Color(255, 255, 255));
        pnlSign.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlSign.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSign, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSign, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 43;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        jPanel4.add(jPanel6, gridBagConstraints);

        txtPassword.setPreferredSize(new java.awt.Dimension(56, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 370;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 301, 0, 0);
        jPanel4.add(txtPassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.ipadx = 390;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 301, 0, 0);
        jPanel4.add(txtRePassword, gridBagConstraints);

        jPanel5.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(190, 237, 253));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setPreferredSize(new java.awt.Dimension(861, 92));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(5, 69, 134));
        jLabel3.setText("M.I.T. Polytechnic,Pune");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 357, 0, 0);
        jPanel7.add(jLabel3, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(5, 69, 134));
        jLabel5.setText("MIT College Road,Rambaugh Colony,Kothrud,Pune,Maharashtra");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 296, 0, 232);
        jPanel7.add(jLabel5, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(5, 69, 134));
        jLabel7.setText("sspp@mitsspp.edu.in     Contact no. 020-30273531");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 333, 15, 0);
        jPanel7.add(jLabel7, gridBagConstraints);

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private BufferedImage linearResizeBi(BufferedImage origin, int width, int height) {
        BufferedImage resizedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = resizedImage.createGraphics();
        float xScale = (float) width / origin.getWidth();
        float yScale = (float) height / origin.getHeight();
        AffineTransform at = AffineTransform.getScaleInstance(xScale, yScale);
        g.drawRenderedImage(origin, at);
        g.dispose();
        return resizedImage;
    }

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    private void txtlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastActionPerformed

    private void tfPhotoBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhotoBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhotoBrowseActionPerformed

    private void tfnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfnameMouseClicked
        tfname.setText("");
        tfname.setForeground(Color.black);
    }//GEN-LAST:event_tfnameMouseClicked

    private void tfnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfnameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameMouseEntered

    private void tfnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfnameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameMousePressed

    private void txtlastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlastMouseClicked
        txtlast.setText("");
        txtlast.setForeground(Color.black);
    }//GEN-LAST:event_txtlastMouseClicked

    private void tfcontactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfcontactMouseClicked
        tfcontact.setText("");
        tfcontact.setForeground(Color.black);
    }//GEN-LAST:event_tfcontactMouseClicked

    private void cbDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDepartmentMouseClicked
        // TODO add your handling code here:
        cbDepartment.setForeground(Color.black);
    }//GEN-LAST:event_cbDepartmentMouseClicked

    private void tfdesignationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfdesignationMouseClicked
        tfdesignation.setText("");
        tfdesignation.setForeground(Color.black);
    }//GEN-LAST:event_tfdesignationMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            JFileChooser chooser = new JFileChooser(System.getProperty("user.dir") + File.separator + "photo" + File.separator);
            chooser.showOpenDialog(null);

            File f = chooser.getSelectedFile();
            System.out.println("" + f);
            tfPhotoBrowse.setText(f.getAbsolutePath());

            BufferedImage image = ImageIO.read(f);//108,124
            image = linearResizeBi(image, 108, 124);
            JLabel lblImg = new JLabel();
            ImageIcon img = new ImageIcon(image);
            lblImg.setIcon(img);
            this.pnlPhoto.add(lblImg);
            this.pnlPhoto.updateUI();

        } catch (Exception ex) {
          
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            JFileChooser chooser = new JFileChooser(System.getProperty("user.dir") + File.separator + "signature" + File.separator);
            chooser.showOpenDialog(null);

            File f = chooser.getSelectedFile();
            System.out.println("" + f);
            tfSignBrowse.setText(f.getAbsolutePath());

            BufferedImage image = ImageIO.read(f);//108,124
            image = linearResizeBi(image, 242, 45);
            //            lblSign.setText("");
            JLabel lblSign = new JLabel();
            lblSign.setIcon(new ImageIcon(image));
            this.pnlSign.add(lblSign);
            this.pnlSign.updateUI();

        } catch (IOException ex) {
           
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        Connection conn = null;
        DaoConnection dao = new DaoConnection();

        if (("".equals(tfname.getText())) || ("".equals(tfcontact.getText()))) {
            JOptionPane.showMessageDialog(null, "Please Enter all the Fields !!!");
        } else {
//            String emailregex = "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
//            Boolean checkEmail = mailtxt.getText().trim().matches(emailregex);

            Pattern pattern = Pattern.compile("\\d{10}");
            Matcher matcherMobile = pattern.matcher(tfcontact.getText());

            Pattern pattern1 = Pattern.compile("^[a-zA-Z]+([\\s][a-zA-Z]+)*$");
            Matcher matcherFName = pattern1.matcher(tfname.getText().trim());

//            Pattern pattern2 = Pattern.compile("^[0-9]+([\\s][0-9]+)*$");
//            Matcher matcherRoll = pattern2.matcher(tfRoll.getText().trim());
            if (!matcherMobile.matches()) {
                JOptionPane.showMessageDialog(null, "Enter Valid Mobile Nuumber !!!");
            } else if (!matcherFName.matches()) {
                JOptionPane.showMessageDialog(null, "Enter Valid First Name !!!");
//            } else if (!matcherRoll.matches()) {
//                JOptionPane.showMessageDialog(null, "Enter Valid Roll number !!!");
            } else {

                FileInputStream input = null;
                FileInputStream input1 = null;
                try {
                    int x = 0;;
                    String s1 = tfname.getText();
                    String s2 = tfcontact.getText();
                    String last = txtlast.getText();
                    String s5 = (String) cbDepartment.getSelectedItem();
                    String s8 = tfPhotoBrowse.getText();
                    input = new FileInputStream(s8);
                    String s9 = tfSignBrowse.getText();
                    String desig = tfdesignation.getText();

                    input1 = new FileInputStream(s9);
                    SimpleDateFormat dt = new SimpleDateFormat("dd-MM-yyyy");
//                    String s10 = dt.format(s3);

                    System.out.println(s1);
                    System.out.println(s2);
                    System.out.println(s5);
                    String first = s1.substring(0, 1).toUpperCase() + s1.substring(1);
                    String lastname = last.substring(0, 1).toUpperCase() + last.substring(1);

                    try {
                        conn = dao.getConnection();
                        PreparedStatement ps;
                        ps = conn.prepareStatement("insert into tbtecher values(?,?,?,?,?,?,?)");
                        if (cbDepartment.getSelectedIndex() == 0) {
                            JOptionPane.showMessageDialog(null, "Please Select Department...");
                        } else {
                            ps.setString(1, first);
                            ps.setString(2, lastname);
                            ps.setString(3, s2);

//                        ps.setString(5, s10);
                            ps.setString(4, s5);
                            ps.setString(5, desig);
//                        ps.setString(8, s5);
//                        ps.setString(9, s6);
//                        ps.setString(10, year);
//                        ps.setString(11, address);
                            ps.setBlob(6, input);
                            ps.setBlob(7, input1);
                            ps.executeUpdate();
                            //                    con.close();
                            x++;
                        }
                        if (x > 0) {
                            JOptionPane.showMessageDialog(null, "Account Created Successfully");
//                            taAddress.setFocusable(false);
                            tfPhotoBrowse.setText("Photo");
                            tfdesignation.setText("Designation");
                            tfSignBrowse.setText("Sign");
                            tfcontact.setText("Contact No.");
                            txtlast.setText("Last Name");
                            tfname.setText("First Name");
//                            txtEnroll.setText(""); 
                            tfPhotoBrowse.updateUI();
                            tfdesignation.updateUI();
                            tfSignBrowse.updateUI();
                            tfcontact.updateUI();
                            tfname.updateUI();
                            txtlast.updateUI();
                            cbDepartment.setSelectedIndex(0);
//                            cbShift.setSelectedIndex(0);
//                            jcYear.setSelectedIndex(0);
//                            taAddress.setText("");
//                            rbFemale.setSelected(false);
//                            rbMale.setSelected(false);
//                            jXDatePickerDOB.removeAll();
//                            jXDatePickerDOB.setDate(null);
//                            this.jXDatePickerDOB.updateUI();
                            this.pnlPhoto.removeAll();
                            this.pnlSign.removeAll();
                            this.pnlPhoto.updateUI();
                            this.pnlSign.updateUI();
                            this.updateUI();
//                            txtEnroll.setRequestFocusEnabled(true);
//                            txtEnroll.setFocusable(true);
//                            taAddress.setFocusable(true);
                            tfcontact.setFocusable(true);

                        }
                    } catch (SQLException | HeadlessException e) {
                        System.out.println(e);
                    }
                } catch (FileNotFoundException ex) {
                   
                } finally {
                    try {
                        input1.close();
                        input.close();

                    } catch (IOException ex) {
                       
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfPhotoBrowse.setText("");
//        tfRoll.setText("");
        tfSignBrowse.setText("");
        tfcontact.setText("");
        tfname.setText("");
//        txtEnroll.setText(""); 
        this.pnlPhoto.removeAll();
        this.pnlSign.removeAll();
        this.pnlPhoto.updateUI();
        this.pnlSign.updateUI();
//        jXDatePickerDOB.removeAll();
        cbDepartment.setSelectedIndex(0);
//        cbShift.setSelectedIndex(0);
//        taAddress.setText("");
        JOptionPane.showMessageDialog(null, "Fields Cleared !!!");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void tfnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfnameKeyPressed
        // TODO add your handling code here:
//        tfname.setText("");
        tfname.setForeground(Color.black);
    }//GEN-LAST:event_tfnameKeyPressed

    private void tfcontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcontactKeyTyped
        // TODO add your handling code here:
//        tfcontact.setText("");
        tfcontact.setForeground(Color.black);
    }//GEN-LAST:event_tfcontactKeyTyped

    private void txtlastKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlastKeyTyped
        // TODO add your handling code here:
//        txtlast.setText("");
        txtlast.setForeground(Color.black);
    }//GEN-LAST:event_txtlastKeyTyped

    private void tfdesignationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdesignationKeyTyped
        // TODO add your handling code here:
//        tfdesignation.setText("");
        tfdesignation.setForeground(Color.black);
    }//GEN-LAST:event_tfdesignationKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRegister;
    public javax.swing.JComboBox cbDepartment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel pnlPhoto;
    private javax.swing.JPanel pnlSign;
    public javax.swing.JTextField tfPhotoBrowse;
    public javax.swing.JTextField tfSignBrowse;
    public javax.swing.JTextField tfcontact;
    public javax.swing.JTextField tfdesignation;
    public javax.swing.JTextField tfname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    public javax.swing.JTextField txtlast;
    // End of variables declaration//GEN-END:variables
}
